### ISSUE TITLE
cAdvisor SELinux enforced and not privileged. Error tmp permission denied.

### ISSUE THREAD

**Issue by jdanielcano** [google/cadvisor#1043]
Hello, 

I am trying to create and configure cAdvisor in our Kubernetes cluster. We want to do it having SELinux in enforced mode and not running the container in privileged mode. When we do it this way, cAdvisor starts at the end but we have may containers created and in exist status fulling the machine:
```
54-1803730bba99_e5a84d0c
1672d96a820f        docker.io/google/cadvisor:latest	   "/usr/bin/cadvisor"      6 minutes ago       Exited (2)
 6 minutes ago                       k8s_cadvisor.357364a1_cadvisor-controller-q1l6v_default_96086bd5-b62b-11e5-8f
54-1803730bba99_9f2a4b7d
512cf30f8076        gcr.io/google_containers/pause:0.8.0   "/pause"                 6 minutes ago       Exited (0)
 6 minutes ago                       k8s_POD.7193ea7b_cadvisor-controller-q1l6v_default_96086bd5-b62b-11e5-8f54-18

....
```
And we are getting all the time the same error:
```
I0108 16:54:51.641676 00001 storagedriver.go:132] No backend storage selected
log: exiting because of error: log: cannot create log: open /tmp/cadvisor.cadvisor-controller-4iwgc.root.log.INFO.20160108-165451.1: permission denied
```

I present the environment I am running the application:

Docker executed command:
```
docker run 
--volume=/var/run:/var/run:rw \
--volume=/sys:/sys:ro \
--volume=/var/lib/docker/:/var/lib/docker:ro \
--publish=9090:4194 \
--name=cadvisor google/cadvisor:latest
```

The same but to create a resource controller and a pod in Kubernetes cluster:
```yaml
---
kind: "ReplicationController"
apiVersion: "v1"
metadata:
  name: "cadvisor-controller"
spec:
  replicas: 1
  selector:
    name: "cadvisor"
  template:
    spec:
      containers:
        - name: "cadvisor"
          image: "docker.io/google/cadvisor:latest"
          logtostderr: true
          privileged: true (to make it works)
          ports:
            - name: http
              containerPort: 4194
          volumeMounts:
          - mountPath: /var/run
            name: varrun
            readOnly: false
          - mountPath: /var/lib/docker
            name: varlibdocker
            readOnly: true
          - mountPath: /var/lib/kubelet
            name: varlibkubelet
            readOnly: false
          - mountPath: /sys
            name: sysfs
            readOnly: true
      restartPolicy: Always
      dnsPolicy: Default
      volumes:
      - name: varrun
        hostPath:
          path: /var/run
      - name: varlibdocker
        hostPath:
          path: /var/lib/docker
      - name: sysfs
        hostPath:
          path: /sys
      - name: varlibkubelet
        hostPath:
          path: /var/lib/kubelet
    metadata:
      labels:
        name: "cadvisor"
  labels:
    name: "cadvisor"
---
```

System:
- OS: CentOS 7.1
- Kernel: 3.10.0-229.20.1.el7.x86_64
- Docker Version: 1.8.2, build bb472f0/1.8.2
- Kubernetes Version: 1.0.3
- cAdvisor container version: lastest (January 2016)

Configuration:
- SELinux: Enforced. We need to have it this way for security reasons. If we change it to permissive or disable, everything works fine, without using the privileged thing.
- Privileged containers: Now, the configuration in the kubernetes cluster does not allow the execution of privileged containers. `KUBE_ALLOW_PRIV="--allow_privileged=false"`. If we run the docker command directly with the flag `--privileged=true` everything works fine.

The error in the SELinux is the following:
```
type=AVC msg=audit(1452270715.477:129855): avc:  denied  { write } for  pid=XXXX comm="cadvisor" name="/" dev="tmpfs" ino=XXXXX scontext=system_u:system_r:svirt_lxc_net_t:s0:c591,c638 tcontext=system_u:object_r:var_run_t:s0 tclass=dir
```

So here is my question:

There would be a way of running the cAdvisor container with SELinux in enforced mode and not allowing privileged mode?

Thanks in advance.
