### ISSUE TITLE
Short lived containers not being captured

### ISSUE THREAD

**Issue by NoumanSaleem** [google/cadvisor#1329]
Hi all,

In our system, we have numerous short lived jobs for which we'd like to confirm have ran using cadvisor/prometheus alerts. One job runs on a 10min interval, and lasts ~20seconds. Unfortunately, we receive a lot of false positives in our current prometheus rule for this job.

The prometheus alert rule:

```
IF absent(count_over_time(container_tasks_state{com_amazonaws_ecs_container_name="populator", state="running"}[10m])) == 1
  FOR 5m
```

When graphing this query in prometheus, I see the gaps in metric data

<img width="1252" alt="screen shot 2016-06-12 at 8 45 07 am" src="https://cloud.githubusercontent.com/assets/694071/15992234/fc44460c-307c-11e6-87f8-2f044e1c7c8a.png">

When viewing the status for the job in the scheduler (which runs the container), I see a very consistent pattern
<img width="144" alt="screen shot 2016-06-12 at 9 08 01 am" src="https://cloud.githubusercontent.com/assets/694071/15992245/44491112-307d-11e6-9e45-453609544a48.png">

cadvisor v0.23.2
docker v1.11.1

Please let me know if you need any more info,
thanks!

**Comment by NoumanSaleem** [comment]
Still dealing with this, so I decided to run a trial.

Locally, I ran the following docker-compose file:
```
cadvisor:
  image: google/cadvisor
  command: --log_cadvisor_usage=true
  ports:
    - "8080:8080"
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

prometheus:
  image: prom/prometheus
  ports:
    - "9090:9090"
  volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
  links:
    - cadvisor
```

With the following `prometheus.yml`
```
global:
  scrape_interval:     1m
  evaluation_interval: 1m

scrape_configs:
  - job_name: 'prom'
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
```

Once prometheus had completed a few scrapes, I ran the following docker-compose file three times consecutively, waiting about a minute between runs.
```
test60:
  image: alpine
  command: /bin/sh -c "sleep 60; exit 0;"

test30:
  image: alpine
  command: /bin/sh -c "sleep 30; exit 0;"

test10:
  image: alpine
  command: /bin/sh -c "sleep 10; exit 0;"
```

Lastly, I queried prometheus using:
```
count_over_time(container_tasks_state{image="alpine",state="running"}[1h])
```

The result showed:
```
Element,Value
{container_label_com_docker_compose_config_hash="b223f362152debbce7399b955ba04ff16e579ab593e9a5e05b7d4c0cc3e983ce",container_label_com_docker_compose_container_number="1",container_label_com_docker_compose_oneoff="False",container_label_com_docker_compose_project="cadvisortest",container_label_com_docker_compose_service="test30",container_label_com_docker_compose_version="1.8.0",id="/docker/82ab6b070a618111e30a8b69ced2022fb31af43fe79eb361140d0efe2acd807f",image="alpine",instance="cadvisor:8080",job="cadvisor",name="cadvisortest_test30_1",state="running"}	1
{container_label_com_docker_compose_config_hash="632f9aabd0b5f54f481338f31ac871ace8d5c5f8f20a21dcd9b3bdeda13378f3",container_label_com_docker_compose_container_number="1",container_label_com_docker_compose_oneoff="False",container_label_com_docker_compose_project="cadvisortest",container_label_com_docker_compose_service="test60",container_label_com_docker_compose_version="1.8.0",id="/docker/14a08442c0848a08549e9c04a652c1611997203f2c41836e8cea047ea8019c7d",image="alpine",instance="cadvisor:8080",job="cadvisor",name="cadvisortest_test60_1",state="running"}	3
{container_label_com_docker_compose_config_hash="89806db0cd00c051cdc4d55f3a8d28e3c11723b994d6c7dc3404fd57ecb90419",container_label_com_docker_compose_container_number="1",container_label_com_docker_compose_oneoff="False",container_label_com_docker_compose_project="cadvisortest",container_label_com_docker_compose_service="test10",container_label_com_docker_compose_version="1.8.0",id="/docker/97d46566140dd6161f36350d47d6e54a63e5b7fe4425584e1f3b2da7d530a247",image="alpine",instance="cadvisor:8080",job="cadvisor",name="cadvisortest_test10_1",state="running"}	1
```

Only the container which ran for 60 seconds was captured all three times. 

If this is not a cadvisor use case, please let me know. I was hoping to use prometheus + cadvisor `container_tasks_state` to alert for short lived jobs not running, instead of adopting the prometheus push gateway.

Other than this, I've had a fantastic experience with cAdvisor. Thank you!
