### ISSUE TITLE
Docker compose authentication

### ISSUE THREAD

**Issue by psychok7** [google/cadvisor#1451]
hi, i am using docker-compose with cadvisor, how can i set authentication using compose??

```
  cadvisor:
    image: google/cadvisor:latest
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
```
