### ISSUE TITLE
Can't get process list working when run in a docker container

### ISSUE THREAD

**Issue by JamesKyburz** [google/cadvisor#1477]
I get the error

`process listing failed: failed to execute "/usr/sbin/chroot" command: exit status 1`

Here is the latest I tested in my docker compose

```
  cadvisor:
    image: google/cadvisor:v0.24.0
    cap_add:
      - all
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /proc:/hostproc:rw
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always
```
