### ISSUE TITLE
allow to disable "container_cpu_usage_seconds_total" metric

### ISSUE THREAD

**Issue by piontec** [google/cadvisor#1513]
I'm running cAdvisor on a 128 CPU core machine with nearly 200 containers. This metric is killing cAdvisor and prometheus, which collects the data. Some statistics about the "/metrics" endpoint:

```
$ ls -sh metrics.txt
19M metrics.txt
```

```
$ wc -l metrics.txt 
64635 metrics.txt
```

```
$ grep "container_cpu_usage_seconds_total" metrics.txt| wc -l
47362
```

So this single metric takes over 70% of the 19MB response. I think it must be possible to disable it.

**Comment by magicrobotmonkey** [comment]
I'm having the same issue. Might I suggest also/instead allowing to collapse to one total cpu usage per container, rather than one per core?

**Comment by magicrobotmonkey** [comment]
Actually, I realized that `container_cpu_system_seconds_total` gives the per-system usage. This means a workaround for this is to just drop the per cpu metrics like so:
```yaml
- job_name: 'mesos-compute-cadvisor'
  metric_relabel_configs:
    - source_labels: [cpu]
      regex: (cpu.*)
      action: drop
```
