### ISSUE TITLE
Help - Missing container's name 

### ISSUE THREAD

**Issue by jmirc** [google/cadvisor#1873]
Hi,

I deployed cAdvisor in a Rancher cluster using the following docker-compose configuration and I am not able to get the container's name
Can you help me to fix the issue?

**Info**

```
Rancher: v1.6.13
Docker Version: 1.12.6
Docker API Version: 1.24
Kernel Version: 3.10.0-693.11.6.el7.x86_64
OS Version: CentOS Linux 7 (Core)
```

**docker-compose.yml**
``` 
  cadvisor:
    privileged: true
    image: google/cadvisor:latest
    stdin_open: true
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /cgroup:/cgroup:ro
    - /var/lib/docker/:/var/lib/docker:ro
    tty: true
    ports:
    - 8080:8080/tcp
    labels:
      io.rancher.scheduler.global: 'true'
```

**cAdvisor /metrics**

```
# HELP cadvisor_version_info A metric with a constant '1' value labeled by kernel version, OS version, docker version, cadvisor version & cadvisor revision.
# TYPE cadvisor_version_info gauge
cadvisor_version_info{cadvisorRevision="1e567c2",cadvisorVersion="v0.28.3",dockerVersion="1.12.6",kernelVersion="3.10.0-693.11.6.el7.x86_64",osVersion="Alpine Linux v3.4"} 1
# HELP container_cpu_load_average_10s Value of container cpu load average over the last 10 seconds.
# TYPE container_cpu_load_average_10s gauge
container_cpu_load_average_10s{id="/"} 0
# HELP container_cpu_system_seconds_total Cumulative system cpu time consumed in seconds.
# TYPE container_cpu_system_seconds_total counter
container_cpu_system_seconds_total{id="/"} 0.98
# HELP container_cpu_usage_seconds_total Cumulative cpu time consumed per cpu in seconds.
# TYPE container_cpu_usage_seconds_total counter
container_cpu_usage_seconds_total{cpu="cpu00",id="/"} 0.700235834
container_cpu_usage_seconds_total{cpu="cpu01",id="/"} 0.535064255
container_cpu_usage_seconds_total{cpu="cpu02",id="/"} 0.509572365
container_cpu_usage_seconds_total{cpu="cpu03",id="/"} 0.646855628
# HELP container_cpu_user_seconds_total Cumulative user cpu time consumed in seconds.
# TYPE container_cpu_user_seconds_total counter
container_cpu_user_seconds_total{id="/"} 1.17
# HELP container_fs_inodes_free Number of available Inodes
# TYPE container_fs_inodes_free gauge
container_fs_inodes_free{device="/dev/mapper/docker-259:2-1627-c36591c389ae705224d34b153bfc61cda5f7943b15440695af8ad893401783c0",id="/"} 5.240956e+06
container_fs_inodes_free{device="/dev/nvme0n1p1",id="/"} 4.1904433e+07
container_fs_inodes_free{device="shm",id="/"} 956222
container_fs_inodes_free{device="tmpfs",id="/"} 956057
```
