### ISSUE TITLE
cannot disable ZFS metrics

### ISSUE THREAD

**Issue by thet** [google/cadvisor#1936]
I run cadvisor via a docker container like this:
```
  cadvisor:
    image: google/cadvisor:latest
    user: root
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /cgroup:/cgroup:ro
      - /dev/zfs:/host/dev/zfs:ro
      - /proc:/host/proc:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run:/var/run:rw
    command:
      # tcp and udp create high CPU usage, disk does CPU hungry ``zfs list``
      - '--disable_metrics=tcp,udp,disk'
    restart: unless-stopped
    ports:
      - 9110:8080
```

cAdvisor does a load-heavy ``zfs list`` which is eating around 40-100% CPU time.
I want to disable it.
the disable-metrics=tcp,udb,disk doesn't seem to have any effect on this.

**Comment by dashpole** [comment]
How are you measuring the CPU usage of zfs list?  Can you tell me a bit more about your setup: How large of a machine/vm, how many containers, and how many zfs pools?

We have assumed up to this point that measuring disk space on a partition/pool is cheap, and running `du` is expensive.  Thus, disabling `disk` just results in the latter being disabled.  I guess this is a case where the former is expensive as well.

We could make disabling `disk` also disable zfs accounting.  I don't know enough about ZFS, but there may be optimizations we could make for ZFS accounting to fox your problem as well.

I would be happy to review a PR for either one

**Comment by bnounours** [comment]
Hello,
I have the same issue. Cadvisor try to get data from zfs but fails and use lots of CPU. I get this log all the time for each dataset : 

`E0721 15:30:16.615631       1 fs.go:418] Stat fs failed. Error: exit status 1: "/usr/sbin/zfs zfs list -Hp -o name,origin,used,available,mountpoint,compression,type,volsize,quota,referenced,written,logicalused,usedbydataset data/docker/lib/1e7524fa964b400881d88c770d67e72c70157cc4d729e92e1b96c13791634a05" => cannot open 'data/docker/lib/1e7524fa964b400881d88c770d67e72c70157cc4d729e92e1b96c13791634a05': dataset does not exist`

Cadvisor himself tell me the docker use ~ 30% CPU

![capture d ecran de 2018-07-21 17-30-56](https://user-images.githubusercontent.com/6874419/43043072-13b947de-8d8b-11e8-874a-63cffbf22b14.png)

Here is my docker-compose file

```
container-exporter:
    image: google/cadvisor
    privileged: true
    command:
      - "--port=9104"
    devices:
      - "/dev/zfs"
    volumes:
      - /:/rootfs:ro
      - /cgroup:/cgroup:ro
      - /dev/zfs:/host/dev/zfs:ro
      - /proc:/host/proc:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run:/var/run:rw
    ports:
      - 9104:9104
```
