### ISSUE TITLE
cadvisor docker container fails to start "mountpoint for cpu not found" (clearcontainers)

### ISSUE THREAD

**Issue by zeigerpuppy** [google/cadvisor#1943]
I am attempting to run cadvisor on Debian Stretch (without systemd).  My docker setup is using [clearcontainers](https://github.com/clearcontainers/runtime) and a backend with block-based sparse LVM storage (layered onto ZFS).  Everything is functioning well with a broad range of containers.

When I try to start cadvisor, it gives the following log output:

```
2018-05-21T08:51:31.105718776Z I0521 08:51:31.085339       1 storagedriver.go:50] Caching stats in memory for 2m0s
2018-05-21T08:51:31.105772425Z F0521 08:51:31.085940       1 cadvisor.go:134] Failed to create a Container Manager: mountpoint for cpu not found
```

I think this may be to do with some difficulties in accessing the volume for `/sys`, perhaps it is not permitted to be shared in this way...

My `docker-compose.yml` is as follows:

```yaml
version: '2'

# this compose file builds cadvisor
# networked on docker2 bridge
# IPs
# 172.18.18.60    cadvisor

services:
    cadvisor:
        restart: always
        image: google/cadvisor:latest
        container_name: cadvisor
        ipc: private
        shm_size: 128M
        networks:
          docker2:
            ipv4_address: 172.18.18.60
        expose:
            - "8080"
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro
            - /zpool2/docker_config/dns/resolv.conf:/etc/resolv.conf
            - /zpool2/docker_config/cache/01proxy:/etc/apt/apt.conf.d/01proxy

networks:
  docker2:
    external:
      name: docker2
```

**Comment by dashpole** [comment]
The volumes look correct... I bet it is related to this [limitation](https://github.com/clearcontainers/runtime/blob/master/docs/limitations.md#docker--v-dev).  You are trying to mount in `/dev/...`, which clearcontainers doesn't support.

**Comment by gregbert42** [comment]
I am getting this same error message. here is the relevant portion of my docker-compose

```
  cadvisor:
    image: google/cadvisor:latest
    container_name: monitoring_cadvisor
    restart: unless-stopped
    devices:
      - "/dev/kmsg:/dev/kmsg"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    expose:
      - 8080
    ports:
      - 8085:8080

```

Here is the error I get:

```
monitoring_cadvisor | F0424 20:46:33.869962       1 cadvisor.go:146] Failed to create a Container Manager: mountpoint for cpu not found
monitoring_cadvisor exited with code 255

```

any ideas?
