### ISSUE TITLE
unable to get processes from cadvisor

### ISSUE THREAD

**Issue by devopsmash** [google/cadvisor#1957]
I'm trying to use the processes metrics in my **Prometheus** from the **cadvisor** the same way that appears in ```http://<my cadvisor server>:9101/containers/ ``` under **Processes** section:

<img width="793" alt="cadvisor" src="https://user-images.githubusercontent.com/22152786/41193213-dc62a766-6c11-11e8-9bb1-02ef46b3ad4e.PNG">

The issue is that I can't find any process with the name "htop" under ```http://<my cadvisor server>:9101/metrics/``` even this process is appear under ```http://<my cadvisor server>:9101/containers/user.slice``` (like the picture above)

example metric from cadvisor that I'm getting:
```
container_cpu_system_seconds_total{container_label_branch_name="",container_label_com_docker_compose_config_hash="",container_label_com_docker_compose_container_number="",container_label_com_docker_compose_oneoff="",container_label_com_docker_compose_project="",container_label_com_docker_compose_service="",container_label_com_docker_compose_version="",container_label_maintainer="",container_label_org_label_schema_group="",container_label_org_label_schema_schema_version="",container_label_service_name="",id="/system.slice/vmware-tools.service",image="",name=""} 39.8
```

I can't even get the other basic columns like PID, command and more of processes

There is any way to expose all the processes to the ```http://<my cadvisor server>:9101/metrics/```  like the same as the picture above using the cadvisor?

I'm using cadvisor with docker-compose:
```
version: '2.3'

services:

  cadvisor:
    image: google/cadvisor:v0.29.0
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    restart: always
    ports:
      - 9101:9101
    networks:
      - monitor-net
    command:
      - '--port=9101'
```
