### ISSUE TITLE
cadvisor consumes super high CPU

### ISSUE THREAD

**Issue by alanh0vx** [google/cadvisor#2049]
I am using DaemonSet to deploy cadvisor (latest image) to monitor the metrics of the k8s pods, there are 3 nodes, and cadvisors on each node are actually working, able to get the metrics, however, 

we found that when it gets metrics, it consumes super high CPU, more than 200%?!
there are around 80 docker containers running on that node.  

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                       
19880 root      20   0 3641356 2.667g   8644 S 283.4 17.0   1:34.46 cadvisor                                                                                                                                  
  668 root      20   0 2258368 417724  14572 S  24.6  2.5   2544:55 kubelet    
```

also found this warning during starting up:
```
 Could not configure a source for OOM detection, disabling OOM events: open /dev/kmsg: no such file or directory
```

Please help, or whether there are any other alternatives.

Thanks a lot!

**Comment by dashpole** [comment]
Try using `--ignore-metrics` to disable metrics you are not using.  Particularly expensive metrics are disk, diskIO, UDP, and tcp metrics.

**Comment by alanh0vx** [comment]
tried to disable several metrics, but it still keeps super high CPU, up to 3xx %

I have also modified `sudo sysctl fs.inotify.max_user_watches=1048576` in order to start the container

here is my deployment:
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: cadvisor
  namespace: kube-system
  labels:
    app: cadvisor
spec:
  selector:
    matchLabels:
      name: cadvisor
  template:
    metadata:
      labels:
        name: cadvisor
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: cadvisor
        image: google/cadvisor:latest
        volumeMounts:
        - name: rootfs
          mountPath: /rootfs
          readOnly: true
        - name: var-run
          mountPath: /var/run
          readOnly: false
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: docker
          mountPath: /var/lib/docker
          readOnly: true
        ports:
          - name: http-cadvisor
            containerPort: 8080
            hostPort: 10255
            protocol: TCP
        args:
          - --allow_dynamic_housekeeping=true
          - --housekeeping_interval=30s
          - --global_housekeeping_interval=2m
          - --disable_metrics=disk,tcp,udp
      terminationGracePeriodSeconds: 30
      volumes:
      - name: rootfs
        hostPath:
          path: /
      - name: var-run
        hostPath:
          path: /var/run
      - name: sys
        hostPath:
          path: /sys
      - name: docker
        hostPath:
          path: /var/lib/docker
---
kind: Service
apiVersion: v1
metadata:
  name: cadvisor
  namespace: kube-system
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    name: cadvisor
  ports:
  - name: http-cadvisor
    protocol: TCP
    port: 10255
```
