### ISSUE TITLE
How to monitor GPU metrics on container level

### ISSUE THREAD

**Issue by Cherishty** [google/cadvisor#2095]
I am a new comer in cadvisor and when I  attempt to deploy [kube-prometheus](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus) on my k8s cluster to monitoring my GPU. There is no **GPU usage** info in container level and machine level. 
My k8s version is  **v1.9.5** and I use Nvidia GPU in container via setting `--feature-aget=Accelerators=true` in kubelet instead of `device-plugin`, It does work when running tensorflow with GPU in container.

I check [Not able to collect metrics for nvidia GPU](https://github.com/google/cadvisor/issues/1912) where @mindprince claimed that 
> GPU monitoring support in Kubernetes was added in 1.9

Also find [add accelerator info to container spec](https://github.com/google/cadvisor/pull/1923) where @mindprince  claimed that 
> cAdvisor only supports container level accelerator metrics

I check the [running.md of cadvisor](https://github.com/google/cadvisor/blob/b26bf6ebb2999de15e6af43337687859a531c4ee/docs/running.md) where said it can support monitoring GPU by adding some parameter when starting cadvisor

So my questions are : 

1.  by default kubelet will start the cadvisor in itself, how to override it to apply **Hardware Accelerator Monitoring** setting in running.md?
2. what are the metrics about GPU usage exposing to cadvisor? I can find some metric like **kube_pod_container_resource_requests_nvidia_gpu_devices** and **kube_node_status_capacity_nvidia_gpu_cards**  in kube-prometheus, but I guess it produced by node-exporter, not cadvisor, am I right?
3. For cadvisor in kubelet,I can only check it on < nodeip >:10255/metrics, but can NOT access < nodeip >:4194, why this happened?

Can anyone kindly gives me a hand since we do really need to monitor our GPU jobs running in k8s? Thanks!

**Comment by Cherishty** [comment]
Hi @WanLinghao  what you mean for /cc ? 
Since we are actively working on exposing GPU to Prometheus, any suggestion or guide?

Best Regards!

**Comment by WanLinghao** [comment]
@Cherishty hello, I am interested in both GPU and cadvisor, I want to know any update about this issue. And I will share if I find any solution about this^_^

**Comment by Cherishty** [comment]
cc @mindprince

**Comment by mindprince** [comment]
https://github.com/google/cadvisor/blob/master/docs/running.md#hardware-accelerator-monitoring has all the details. You need to make sure that however you are running cAdvisor, it satisfies the two conditions mentioned there: access to NVML library and access to GPU devices.

If you are running cAdvisor embedded into the kubelet, then kubelet should have access to NVML library (i.e. its LD_LIBRARY_PATH should contain the location where nvml is present.) Similarly, it should have access to GPU devices.

If you are running cAdvisor/kubelet inside a container itself, things are complicated but the two requirements are the same. The link above explains how to satisfy these two requirements when running cAdvisor inside the container.

It's hard to debug individual cases without access to the environment.

**Comment by dashpole** [comment]
I got a container running using NVML a couple weeks ago: https://github.com/dashpole/example-gpu-monitor/blob/master/deploy/kubernetes/daemonset.yaml.  It probably isn't a great example in terms of security, as it just makes the pod privileged, but it is somewhere to start.

**Comment by Cherishty** [comment]
Quite appreciate for your attention and help!
@dashpole  I have a try on your solution, checking the log of pod I believe it has detected the GPU, then where it exposes the metrics to and how can I check it?

@mindprince  Yes, for **embedded** cAdvisor, I have set the right LD_LIBRARY_PATH, I am not sure what you mean for  **have access to** GPU devices but it should be since tensorflow training for GPU can run successfully on my GPU node. Additionally, may you double confirm what is the metrics representing for GPU? 
Following the context in [issue 1912](https://github.com/google/cadvisor/issues/1912), seems it should be container_accelerator_xxx, but I didn't find clu like this on my <gpu_node_ip>::10255/metrics/cadvisor


Thanks !!!

**Comment by dashpole** [comment]
@Cherishty just exec into the pod, and `wget` or `curl` `localhost:8080/metrics`, and look for the `container_accelerator`... metrics.  It is also worth noting that cAdvisor only monitors GPUs being used by containers, so make sure a container is running using the GPU when you are looking for metrics

**Comment by Cherishty** [comment]
@dashpole  Thanks for your guidance.
While it returns nothing when I running `wget localhost:8080/metrics` , I check the log which reports that:

> [root@stcal-102 ~]# kubectl log nvidia-gpu-monitoring-daemonset-4fgp6 -n monitoring
> W1116 10:40:48.336472  105667 cmd.go:353] log is DEPRECATED and will be removed in a future version. Use logs instead.
> I1113 15:14:59.103954       1 main.go:41] Starting example-gpu-monitor
> I1113 15:14:59.798777       1 stats.go:56] NVML initialized. Number of nvidia devices: 1
> W1113 15:14:59.804360       1 util_unix.go:75] Using "/podresources/kubelet.sock" as endpoint is deprecated, please consider using full url format "unix:///podresources/kubelet.sock".
> E1116 01:59:52.948493       1 metrics.go:71] error getting devices from the kubelet: &{0xc0002101e0}.Get(_) = _, rpc error: code = Unavailable desc = grpc: the connection is unavailable

Any clues or ideas?

**Comment by dashpole** [comment]
Please do not use the example GPU monitor.  I just shared that as an example of how to get NVML to work from inside a container.  I am adding [this patch](https://github.com/google/cadvisor/pull/2101/files#diff-e8b0914c0675ff9f8d8f4b2710b6fb36) for the [cAdvisor daemonset](https://github.com/google/cadvisor/tree/master/deploy/kubernetes#cadvisor-kubernetes-daemonset) to show how to get cAdvisor working.

**Comment by dashpole** [comment]
It shouldn't matter how your container is consuming GPUs.  cAdvisor interacts directly with the cgroup tree.

**Comment by Cherishty** [comment]
@dashpole I can not appreciate more for your patient clarification and guidance!
Following your words I try Kustomize with your patch and generate below cadvisor.yaml:
```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: cadvisor
  name: cadvisor
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: docker/default
  labels:
    app: cadvisor
  name: cadvisor
  namespace: cadvisor
spec:
  selector:
    matchLabels:
      app: cadvisor
      name: cadvisor
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        app: cadvisor
        name: cadvisor
    spec:
      automountServiceAccountToken: false
      containers:
      - args:
        - --housekeeping_interval=10s
        - --max_housekeeping_interval=15s
        - --event_storage_event_limit=default=0
        - --event_storage_age_limit=default=0
        - --disable_metrics=percpu,disk,network,tcp,udp
        - --docker_only
        env:
        - name: LD_LIBRARY_PATH
          value: /bin/nvidia/lib64/
        image: k8s.gcr.io/cadvisor:v0.30.2
        name: cadvisor
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 300m
          requests:
            cpu: 150m
            memory: 200Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev
          name: dev
        - mountPath: /bin/nvidia/lib64/
          name: libnvidia
        - mountPath: /rootfs
          name: rootfs
          readOnly: true
        - mountPath: /var/run
          name: var-run
          readOnly: true
        - mountPath: /sys
          name: sys
          readOnly: true
        - mountPath: /var/lib/docker
          name: docker
          readOnly: true
        - mountPath: /dev/disk
          name: disk
          readOnly: true
      - command:
        - /monitor
        - --stackdriver-prefix=custom.googleapis.com
        - --source=cadvisor:http://localhost:8080
        - --pod-id=$(POD_NAME)
        - --namespace-id=$(POD_NAMESPACE)
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: gcr.io/google-containers/prometheus-to-sd:v0.2.6
        name: prometheus-to-sd
        ports:
        - containerPort: 6061
          name: profiler
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      priorityClassName: system-node-critical
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - hostPath:
          path: /dev
        name: dev
      - hostPath:
          path: /usr/lib64/nvidia
        name: libnvidia
      - hostPath:
          path: /
        name: rootfs
      - hostPath:
          path: /var/run
        name: var-run
      - hostPath:
          path: /sys
        name: sys
      - hostPath:
          path: /var/lib/docker
        name: docker
      - hostPath:
          path: /dev/disk
        name: disk

```

While it occurs **CrashLoopBackOff** and I collect the error log as below:

```
kubectl log -p cadvisor-9pl2f -n cadvisor
I1119 07:49:56.632813       1 manager.go:233] Version: {KernelVersion:3.10.0-862.14.4.el7.x86_64 ContainerOsVersion:Alpine Linux v3.7 DockerVersion:1.12.6 DockerAPIVersion:1.24 CadvisorVersion:v0.30.2 CadvisorRevision:de723a09}
E1119 07:49:56.674977       1 factory.go:340] devicemapper filesystem stats will not be reported: usage of thin_ls is disabled to preserve iops
I1119 07:49:56.675983       1 factory.go:356] Registering Docker factory
I1119 07:49:56.676199       1 factory.go:54] Registering systemd factory
I1119 07:49:56.678237       1 factory.go:86] Registering Raw factory
I1119 07:49:56.680433       1 manager.go:1205] Started watching for new ooms in manager
I1119 07:49:56.820255       1 nvidia.go:100] NVML initialized. Number of nvidia devices: 1
I1119 07:49:56.827148       1 manager.go:356] Starting recovery of all containers
I1119 07:49:58.522108       1 manager.go:361] Recovery completed
F1119 07:49:58.727346       1 cadvisor.go:159] Failed to start container manager: inotify_add_watch /sys/fs/cgroup/cpuacct,cpu: no such file or directory
```

and
```
[root@stcal-102 ~]# kubectl log -p cadvisor-9pl2f -n cadvisor  prometheus-to-sd
W1119 15:50:15.588580   69321 cmd.go:353] log is DEPRECATED and will be removed in a future version. Use logs instead.
F1119 07:49:57.880255       1 main.go:82] Failed to get GCE config: Not running on GCE.
```

Seems `securityContext: privileged: true` is lost in the generated yaml?
Any clues or suggestion?
