### ISSUE TITLE
The relationship between huge CPU usage and options

### ISSUE THREAD

**Issue by k0nstantinv** [google/cadvisor#2144]
Hi, i have been using cAdvisor as a DaemonSet in Kubernetes cluster. My cluster consist of 100 nodes, each of the nodes in turn has ~80 pods. Each of the nodes is a high perfomance 'bare metal' server. DaemonSet deployed without any limits (i mean k8s limits) and here it is:

```
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: cadvisor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: cadvisor
  template:
    metadata:
      labels:
        app: cadvisor
      name: cadvisor
    spec:
      tolerations:
      - operator: Exists
      containers:
      - name: cadvisor
        args:
          - --disable_metrics=disk,udp,percpu # enable only tcp
          - --docker_only
          - --housekeeping_interval=30s
          - --max_housekeeping_interval=60s
        image: k8s.gcr.io/cadvisor:v0.30.2
        resources:
          requests:
            cpu: 1000m
            memory: 512Mi
        volumeMounts:
        - name: var-run
          mountPath: /var/run
          readOnly: true
        - name: docker
          mountPath: /var/lib/docker
          readOnly: true
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: rootfs
          mountPath: /rootfs
          readOnly: true
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 30
      volumes:
      - name: var-run
        hostPath:
          path: /var/run
      - name: docker
        hostPath:
          path: /var/lib/docker
      - name: sys
        hostPath:
          path: /sys
      - name: rootfs
        hostPath:
          path: /
```
As you can see I have already set up the `--disable-metrics` argument to the cAdvisor container. The only thing i need from the cAdvisor is a Prometheus metric `container_network_tcp_usage_total`, so everything except the TCP has been disabled. (Disabling metrics doesn't exclude them from the `/metrics` endpoint or causing them to be zero every time, by the way)

Before the main questions i'd like to show this:
- cAdvisor pod with the highest CPU usage across the cluster consumes almost 3 cores:
```
NAME             CPU(cores)   MEMORY(bytes)
cadvisor-whm2v   2795m        837Mi
```
- cAdvisor pod with the lowest CPU usage across the cluster consumes less then 2% of a single core:
```
NAME             CPU(cores)   MEMORY(bytes)
cadvisor-qzlv6   13m          39Mi
```

 I've already read the similar issues here and i noticed some advises:
1) >Try using --ignore-metrics to disable metrics you are not using. Particularly expensive metrics are disk, diskIO, UDP, and tcp metrics.
2) >I would recommend increasing housekeeping even higher to 10s

`--ignore_metrics` option doesn't exist in my version
`--disable_metrics` option  has only: `'disk', 'network', 'tcp', 'udp', 'percpu'`
`--housekeeping_interval` is already a 30s

So, i completely don't understand:
- why `--disable_metrics` option has `network` and `tcp,udp` at the same time? I suggested `network` is a `tcp+udp`, but metric `container_network_tcp_usage_total` is always zero without enabled `network`
- why the CPU usage of this two particular pods is so different? The two pods above are the part of the same DaemonSet.
- what should i do to minimise CPU usage of my pods?
- now I must drop unnecessary metrics in the Prometheus and it was the best bad idea I could come up with. What is the best way to completely disable everything I don't need on the cAdvisor's side (including the `/metrics` endpoint)?
