### ISSUE TITLE
Could not configure a source for OOM detection, disabling OOM events

### ISSUE THREAD

**Issue by wongchao** [google/cadvisor#2150]
rancher1.6

Ubuntu 16.04.2
4.4.0-62-generic
Docker version 17.12.1-ce, build 7390fc6
google/cadvisor:v0.32.0

volumn:
                "/:/rootfs:ro",
                "/var/run:/var/run:rw",
                "/sys:/sys:ro",
                "/var/lib/docker/:/var/lib/docker:ro",
                "rancher-cni:/.r:ro"

logs:
2019/1/18 下午6:12:08W0118 10:12:08.685620       1 manager.go:349] Could not configure a source for OOM detection, disabling OOM events: open /dev/kmsg: no such file or directory

**Comment by CpuID** [comment]
Tried that, same outcome. Tried it RO and RW.

**Comment by tommmlij** [comment]
Run the cadvisor container with ```privileged: true```

**Comment by torhoehn** [comment]
@tommmlij That was working for me.

**Comment by lizibin** [comment]
@wongchao  我也遇到同样的问题，你解决了吗？

**Comment by ZVilusinsky** [comment]
`privileged: true` does not work/is not enough on Centos 7.7

Metrics flow and work without privileged, but following running instructions results in `Could not configure a source for OOM detection, disabling OOM events: open /dev/kmsg: no such file or directory`
Mounting /dev instead of /dev/disk changes it to `Could not configure a source for OOM detection, disabling OOM events: open /dev/kmsg: operation not permitted` 
Turning privileged on/off does not seem to affect it in any way.

**Comment by jamesdboone** [comment]
Probably better to use --device tag to mount device into container than using privileged...

**Comment by shrinidhi111** [comment]
> Run the cadvisor container with `privileged: true`

How do I run it as privileged? I am already running it as sudo.

**Comment by dashpole** [comment]
https://kubernetes.io/docs/concepts/workloads/pods/pod/#privileged-mode-for-pod-containers

**Comment by katarzyna-z** [comment]
@dashpole Do you think that we should add --privileged to example command of running cAdvisor in docker in https://github.com/google/cadvisor/blob/master/README.md?

**Comment by katarzyna-z** [comment]
I see that issue don't appear if  `/dev/kmsg` is added to container, for example:
```
VERSION=v0.35.0 # use the latest release version from https://github.com/google/cadvisor/releases
sudo docker run \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:ro \
  --volume=/sys:/sys:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --volume=/dev/disk/:/dev/disk:ro \
  --publish=8080:8080 \
  --name=cadvisor \
  --device=/dev/kmsg \
  gcr.io/google-containers/cadvisor:$VERSION
```

**Comment by avimanyu786** [comment]
> I see that issue don't appear if `/dev/kmsg` is added to container, for example:
> 
> ```
> VERSION=v0.35.0 # use the latest release version from https://github.com/google/cadvisor/releases
> sudo docker run \
>   --volume=/:/rootfs:ro \
>   --volume=/var/run:/var/run:ro \
>   --volume=/sys:/sys:ro \
>   --volume=/var/lib/docker/:/var/lib/docker:ro \
>   --volume=/dev/disk/:/dev/disk:ro \
>   --publish=8080:8080 \
>   --name=cadvisor \
>   --device=/dev/kmsg \
>   gcr.io/google-containers/cadvisor:$VERSION
> ```

On Docker Compose, the solution to this issue is to add the `devices` configuration option:

```
    devices:
      - /dev/kmsg:/dev/kmsg
```
It's no longer reported in the logs after I added this to my docker-compose file.

**Comment by WolfspiritM** [comment]
For anyone having the same problem trying to get this working in docker swarm.
As docker swarm doesn't support devices yet I've managed to get it running via:

``` yaml
version: "3.7"

services:
  cadvisor:
    image: docker
    volumes: 
        - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["/bin/sh","-c"]
    networks:
    - monitoring
    deploy:
      mode: global
    environment:
      - PARENT={{.Task.Name}}
      - CHILDNAME={{.Service.Name}}_sidecar.{{.Node.ID}}.{{.Task.ID}}
      - CADVISOR_VERSION=v0.37.5
    command: 
    - |
      exec docker run -i --rm --network="container:$${PARENT}" \
            --volume=/:/rootfs:ro \
            --volume=/var/run:/var/run:ro  \
            --volume=/sys:/sys:ro  \
            --volume=/var/lib/docker/:/var/lib/docker:ro \
            --volume=/dev/disk/:/dev/disk:ro \
            --name $${CHILDNAME} \
            --privileged \
            --device=/dev/kmsg \
            gcr.io/cadvisor/cadvisor:$${CADVISOR_VERSION}
```

What this does is run a simple unprivileged container which has access to the docker sock of the host. It then calls docker run for cadvisor and attaches cadvisor to the same network as the currently running container. That's all it does. If the service container is stopped cause of the exec the sigterm is passed to the docker run causing both services to be shut down cleanly and the sidcard container gets removed leaving no trace.

Cause the cadvisor sidecar container is attached to the service container network it can then be reached from e.g. prometheus via http://STACK_cadvisor:8080

Hope that helps anyone.
