### ISSUE TITLE
Different disk usage when store to InfluxDB

### ISSUE THREAD

**Issue by loblab** [google/cadvisor#2151]
## Disk usage cAdvisor web UI reported
<img width="831" alt="screen shot 2019-01-20 at 6 03 25 pm" src="https://user-images.githubusercontent.com/11693722/51437776-c762c580-1cdd-11e9-9fbc-f5147a5643a4.png">

## Disk usage stored in InfluxDB

Notice /dev/sdb2 (yellow), only this disk is different, others are consistent.
<img width="584" alt="screen shot 2019-01-20 at 6 07 43 pm" src="https://user-images.githubusercontent.com/11693722/51437814-5a9bfb00-1cde-11e9-9dbd-c98a8781a56d.png">

## Disk usage host reported
Same as the web UI of cAdvisor. So only the usage of /dev/sdb2 stored to InfluxDB is inconsistent. Why?

<img width="856" alt="screen shot 2019-01-20 at 6 11 47 pm" src="https://user-images.githubusercontent.com/11693722/51437866-f0d02100-1cde-11e9-87fa-d0385fdfbf9b.png">

## Environments

- Host: Ubuntu 18.04.1 LTS
- Docker: docker 18.06.1-ce, API 1.38, go1.10.4
- cAdvisor: latest stable  (1/20/2019)

docker-compose.yml:

```
services:
    cadvisor:
        image: google/cadvisor
        hostname: cadvisor
        container_name: lab-cadvisor
        ports:
            - "8080:8080"
        volumes:
            - "/:/rootfs:ro"
            - "/var/run:/var/run:ro"
            - "/sys:/sys:ro"
            - "/var/lib/docker:/var/lib/docker:ro"
            - "/dev/disk:/dev/disk:ro"
        command: [ "-storage_driver=influxdb", "-storage_driver_db=cadvisor", "-storage_driver_host=influxdb:8086" ]
```

Query (in Grafana):
```
SELECT mean("value") FROM "fs_usage" WHERE $timeFilter GROUP BY time($__interval), "device" fill(null)
```
Disk partitions:
<img width="488" alt="screen shot 2019-01-20 at 6 36 55 pm" src="https://user-images.githubusercontent.com/11693722/51438095-7acdb900-1ce2-11e9-8d4b-97d62a24447e.png">
