### ISSUE TITLE
metric container_file_descriptors is 0 when running cadvisor inside a container

### ISSUE THREAD

**Issue by snowmansora** [google/cadvisor#2250]
When running cadvisor inside a container via:
```
docker run \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:ro \
  --volume=/sys:/sys:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --volume=/dev/disk/:/dev/disk:ro \
  --volume=/cgroup:/sys/fs/cgroup:ro \
  --detach=true \
  --privileged=true \
  google/cadvisor:v0.33.0 \
  --disable_metrics=tcp,udp,disk
```
All values of metric container_file_descriptors is 0 (except 1 entry has value of /rootfs/proc/1/fd).

After taking a quick look, I think the problem is https://github.com/google/cadvisor/blob/cc445b9cc7e20e12062cc40ac0aa2b88c40dc487/container/libcontainer/handler.go#L145 is reading /rootfs/cgroup/cpu/cgroup.procs which is an empty file, hence it is not able to get all the pids to calculate the fdCount in https://github.com/google/cadvisor/blob/cc445b9cc7e20e12062cc40ac0aa2b88c40dc487/container/libcontainer/handler.go#L160-L168.

Metric container_file_descriptors is fine when running cadvisor on host.

Wondering anyone has any ideas / hints on making metric container_file_descriptors work when cadvisor is inside a container.

Thanks in advance.

**Comment by dashpole** [comment]
Does the file have the proper value outside of the container?  `cat /sys/fs/cgroup/cpu/cgroup.procs`

**Comment by snowmansora** [comment]
Hi @dashpole,

My host is running Amazon Linux AMI release 2018.03 and does not has `/sys/fs/cgroup/cpu/cgroup.procs`, but `cat /cgroup/cpu/cgroup.procs` does has a list of PIDs.

Inside the container, the code is trying to read the following files:

- /rootfs/cgroup/cpu/cgroup.procs
- /rootfs/cgroup/cpu/docker/6ea6fb20886806a255f3b34ba91b27e3e017a7fa3f35576a30e09b5eaa338bec/cgroup.procs

But those files are empty =(.

**Comment by snowmansora** [comment]
Also tried on CentOS 7 and Ubuntu 16.04, for files:

- /sys/fs/cgroup/cpu,cpuacct/docker/dde90c8d0dfd1e9430f477a6fe6886498331a34d77379d2cc0aec04cc4cdce10/cgroup.procs
- /sys/fs/cgroup/cpu,cpuacct/cgroup.procs

It has PIDs on host, but not inside container.

**Comment by arahimli-dw** [comment]
Seems like we are running into the same issue: https://github.com/google/cadvisor/issues/2251

**Comment by Tab-ops** [comment]
I started the cadvisor with docker, but my container_ file_ The descriptors indicator is 0. I don't know why
```
version: '3'
services:
  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - '28080:8080'
    command: "--disable_metrics='udp'"
    privileged: true
    restart: unless-stopped
```
