### ISSUE TITLE
container_processes metrics are not exported

### ISSUE THREAD

**Issue by Srinivasa633** [google/cadvisor#2258]
I installed cAdvisor as docker container in my mac. I am not able to see "container_processes" metrics in prometheus as well as cAdvisor dashboard is also not showing process related information. Can you please let me know if i need to enable any configs for this. 
Below is my cAdvisor configs.

```
cadvisor:
    image: google/cadvisor:beta
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 8080:8080
    restart: always
    deploy:
      mode: global
```
