### ISSUE TITLE
cadvisor status complete in swarm cluster

### ISSUE THREAD

**Issue by jchorier** [google/cadvisor#2310]
Hi, since few day all my cadvisor containers in my swarm cluster are in complete state. so no container running et no more metrics into prometheus.

```
Docker version 18.09.6 swarm
OS Ubuntu 18.04.2 LTS (GNU/Linux 4.18.0-1025-azure x86_64)
```

how is configured 
```
cadvisor:
    image: google/cadvisor:v0.33.0
    command: -logtostderr -docker_only
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - agent_network
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
```

no log are available so I modified the conf to add -v=4 parameter
so I have some logs but nothing readable for me
I restart the container , the docker deamon, redeploy the stack, upgrade docker deamon to 19.03.1 but nothing works

complete log 
[cadvisor.log](https://github.com/google/cadvisor/files/3600249/cadvisor.log)
there is a lot of msg like 
Factory "docker" was unable to handle container "/"
Factory "containerd" was unable to handle container "/"
Error trying to work out if we can handle /: / not handled by systemd handler

Any Ideas on how to fix this issue ? or a workaround ?

thanks
