### ISSUE TITLE
No Hostname at /metrics when running in docker swarm

### ISSUE THREAD

**Issue by kaytrance** [google/cadvisor#2375]
I am trying to run cadvisor globally on every node in my swarm. To visualize data properly in Prometheus I need a `hostname` to be along with metrics.

Stack config:
```
services:
  cadvisor:
    image: google/cadvisor
    command: -logtostderr -docker_only
    hostname: '{{.Node.Hostname}}'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 7778:8080
    networks:
      - prometheus_net
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  prometheus:
    ...
```

In this stack there's a Prometheus instance running that uses service discovery to get all nodes where cadvisor is running and get all metrics from them:

```
  - job_name: "cadvisor"
    dns_sd_configs:
     - names: ['tasks.cadvisor']
       type: 'A'
       port: 8080
```

Later on if we inspect `cadvisor_version_info` metrics, that should contain hostname, we can see that there are no labels with hostname (formatted a bit so not to be in one line):
```
cadvisor_version_info{
  cadvisorRevision="8949c822",
  cadvisorVersion="v0.32.0",
  dockerVersion="19.03.5",
  instance="10.0.11.9:8080",
  job="cadvisor",
  kernelVersion="3.10.0-693.el7.x86_64",
  osVersion="Alpine Linux v3.7"
}
```

No matter what I do I still cannot get a proper `hostname` to be somewhere within any metric collected from cadvisor.

Please help, I haven't found any documentation how to make it properly. 

Thank you!
