### ISSUE TITLE
How to enable container_spec_memory_limit_bytes metric (shows only 0)

### ISSUE THREAD

**Issue by NikolayShama** [google/cadvisor#2385]
How to enable container_spec_memory_limit_bytes metric (shows only 0). Limits define into ECS definition task.

**Comment by dashpole** [comment]
Do you know what ECS uses to limit memory?  cAdvisor looks at the memory.limit_in_bytes in the container cgroup.

**Comment by NikolayShama** [comment]
> Do you know what ECS uses to limit memory? cAdvisor looks at the memory.limit_in_bytes in the container cgroup.

Yes, I know and sure it does not matter. Maybe cAdvisor should be run with a special parameter to activate this feature?

**Comment by dashpole** [comment]
cAdvisor collects memory metrics by default, so there aren't any additional flags you need to set to get that metric.

**Comment by fredbcode** [comment]
Same here, works with your "old" docker image v0.38.6, tagged latest 
But only 0 with v0.47.2

Of course with exactly the same configuration  

```
  cadvisor:
    image: inetrnalregistry/cadvisor:latest
    container_name: cadvisor
    command:
      - '--docker_only'
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/sys:/sys:ro"
      - "/dev/disk:/dev/disk:ro"
    restart: always          
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - sup 
    privileged: true
    devices: 
      - "/dev/kmsg"
```
Logs:

v0.38.6
```
 docker logs cadvisor
W0202 11:59:24.787107       1 manager.go:159] Cannot detect current cgroup on cgroup v2
```
v0.47.2

```
cadvisor         | W0202 12:06:10.340486       1 machine_libipmctl.go:64] There are no NVM devices!
```
