### ISSUE TITLE
(Relatively) high CPU usage for the cadvisor container

### ISSUE THREAD

**Issue by immortaly007** [google/cadvisor#2523]
I noticed that the CPU usage of cadvisor is the highest of all containers I'm running, which I feel is unexpected. it's still not crazy (an average of 7%), but I feel it should be less.

I'm using the following query to calculate CPU usage (in grafana):
```
sum(rate(container_cpu_usage_seconds_total{image!=""}[1m])) by (id,name)
```

Some info about my instance:

- Prometheus is querying the metrics every 15 seconds. I was querying every 5 seconds before, which lead to 15% CPU usage.
- Cadvisor runs using the arguments: `-docker_only --disable_metrics disk,tcp,udp`
- There are a total of 29 running docker containers
- The host is using a dual core Intel(R) Celeron(R) CPU G1610 @ 2.60GHz, and has 8GB of RAM (which is approximately half filled by the other containers). 
 - Running Debian 10

Is this the expected CPU usage? Is there something I can improve? Or am I monitoring CPU usage wrong?

Edit: I managed to bring it down to ~3% by setting the `--housekeeping_interval` to `10s`. But it would be nice if it was even lower.

**Comment by dashpole** [comment]
you should add a number of things to the disable_metrics list.  See the help text for the flag: https://github.com/google/cadvisor/blob/master/cmd/cadvisor.go#L137

**Comment by kassyss** [comment]
I am also experiencing this issue.
On a small server (with CPU: Quad Core Intel Xeon E3-1265L V2) even i have disabled a large number of metrics, cAdvisor is using an average of 8% cpu. Compared to the other containers, it is at least 8 times higher than the most consuming container.

That's annoying to have the monitoring tool to eat far more resources than the monitored containers.

Best regards

**Comment by gowrisankar22** [comment]
@dashpole I have a docker-compose set up for caadvisor. where to add --housekeeping_interval to 10s ?

**Comment by dashpole** [comment]
@gowrisankar22 to the container args.  I'm not sure where those are specified...

**Comment by kassyss** [comment]
@gowrisankar22 This issue is about high cpu usage, not about docker-compose content.
anyway

```
#  cadvisor:
#    image: gcr.io/google-containers/cadvisor:v0.36.0
#    container_name: cadvisor
#    command:
#      - '--housekeeping_interval=55s'
#      - '--docker_only'

```

**Comment by immortaly007** [comment]
I've disabled all statistics listed, specifically:
`disk,diskIO,network,tcp,udp,percpu,sched,process`

Note that the statistics cpu_topology and hugetlb and referenced_memory were mentioned, but i couldn't actually disable them: it gave me an error about an invalid argument.

Now the CPU usage is down to ~1.5%. This is still the highest average CPU usage of all 31 containers running on my machine (followed by promotheus itself at ~1.3%). 

But I wouldn't say the issue is quite resolved: I expect cadvisor to be able to report statistics with intervals of ~15-30 seconds, without taking more than 1% of the CPU load/time, and I didn't expect to have to disable all statistics I can to get near that number.

**Comment by dashpole** [comment]
1% of how many cores?  Also, the query interval isn't what really matters; it is the housekeeping interval.  cAdvisor collects metrics in the background, and serves them from its cache.

**Comment by immortaly007** [comment]
The machine has two cores, so I believe it would be ~1.5% of a single core. It is calculated as:
`sum(rate(container_cpu_usage_seconds_total{image!=""}[1m])) by (id,name)`

I have set the housekeeping interval to 15s to achieve the 1.5% of two cores CPU usage; The query interval in promotheus indeed appears to be less significant. 

With default settings, cadvisor would take up ~15% CPU usage, which in my opinion is too much for the default settings.

**Comment by tehniemer** [comment]
I'm having this same problem and followed the suggestions in this issue and it corrected it for a while, but the high CPU use came back after restarting the container.
![Image 1597870017](https://user-images.githubusercontent.com/11021632/90692825-6b567f00-e23b-11ea-81b3-3d2920f380e7.png)

This is my docker-compose.
```
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    restart: always
    command: 
      - '--docker=tcp://socket-proxy:2375'
      - '--housekeeping_interval=15s'
      - '--docker_only=true'
      - '--disable_metrics=disk,network,tcp,udp,percpu,sched,process'
    networks:
      - socket_proxy
      - database
    depends_on:
      - socket-proxy
      - prometheus
    security_opt:
      - no-new-privileges:true
    ports:
      - '$CADVISOR_PORT:8080'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /dev/disk/:/dev/disk:ro
```

**Comment by idontusenumbers** [comment]
It seems concerning that a tool that is a fraction of the functionality of a task manager use ~15% CPU tracking the bare essentials of CPU, Memory, and Network. I had to turn down the reporting frequency to something I think is pretty unreasonable (30s) to get it to a comfortable level.

The reduction in cadvisor's CPU usage has coincided with a reduction of TeamCity server CPU usage (also running as a container in docker), which I believe also tracks CPU usage of the 'host' machine. Maybe the CPU tracking of both is playing off each other in a bad way?

**Comment by idontusenumbers** [comment]
> @idontusenumbers, have you tried to enable profiling and see what makes cAdvisor to use that much resources?

I have not. I have no experience doing go dev or native profiling; just JS, Java, and PHP. I'd be happy to help if the issue can't be reproduced, but I'm going to need some guidance.

**Comment by iwankgb** [comment]
@idontusenumbers you need to add argument `-profiling` to your `cadvisor` invocation and navigate to `IP`:`PORT`/debug/pprof/profile?seconds=300. It will generate profile for 300 seconds of cAdvisor execution. After 300 seconds a file will be sent to you - download it and then navigate to the directory where the file is saved and execute: `go tool pprof profile` (`profile` is default name for the downloaded file). It will open profiling console. Type `web` and hit enter. After some time a browser should be opened on your system and you should execution profile for your instance.

**Comment by paaacman** [comment]
Thanks @iwankgb, I made some tests with differents settings, with 60s profiles.
I compare mainly "Total samples" time, and I monitor CPU usage with `htop` and Prometheus `rate(container_cpu_user_seconds_total{name="cadvisor"}[1m]) * 100`. 
For every test, I change only 1 parameter. Almost all tests are made with `-housekeeping_interval=1s`.

My observations, so far, are : 
- `'-docker_only=true'` is the most efficient change. The "Total samples" time go from 8.89s to 2.60s when I add this configuration.
- `'--disable_metrics=disk,network,tcp,udp,percpu,sched,process'` does not help, and can be worst.
- Modifying Prometheus `scrape_interval` can help : from 5s to 45s it make a big difference (from 2.46s to 1.53s) but if it's more than 30s, Prometheus and Grafana will only show dots in graphs (with `rate(container_cpu_user_seconds_total{name="cadvisor"}[1m]) * 100`). I keep `scrape_interval: 15s` and don't understand exactly what `scrape_interval` does.
- Finally, `housekeeping_interval` from 1s (Total samples=2.0s) to 5s (Total samples=0.7s) and 10s (0.6s) make a big difference too.

My final configuration : 
```yml
# docker-compose.yml
...
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /sys/fs/cgroup:/cgroup:ro
      - /dev/disk/:/dev/disk:ro
    command:
      - '-housekeeping_interval=10s'
      - '-docker_only=true'
    restart: unless-stopped
    devices:
      - /dev/kmsg:/dev/kmsg
    security_opt:
      - no-new-privileges:true
    expose:
      - 8080
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
...
```

```yml
# prometheus.yml
...
scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']
...
```
More details about this configuration here https://github.com/paaacman/dockprom.

**Comment by setop** [comment]
> ...
> My observations, so far, are :
> ...
> More details about this configuration here https://github.com/paaacman/dockprom.

Thanks you very much for these advises. When applied, I drop form 8% CPU usage by cadvisor to 0.6% ; much more sustainable.

**Comment by Herz3h** [comment]
Is it  `-housekeeping_interval=1m` or `--housekeeping_interval=1m` @paaacman (1 or 2 dash)

I don't see any difference when using housekeeping_interval and docker_only. Still high cpu usage 100% without around 100 dockers to monitor, using 0.38.8 version :/

**Comment by paaacman** [comment]
As you concluded, it's with 1 dash.
You have a lot of dockers, I have only 10-15, maybe it's a lot more consuming ?
I don't know if it's fetching states "per container" or "per host".

**Comment by JMLX42** [comment]
Here is the configuration I'm using:

```yaml
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.38.8
    command:
      - '-allow_dynamic_housekeeping=false'
      - '-housekeeping_interval=10s'
      - '-docker_only=true'
    restart: unless-stopped
    devices:
      - /dev/kmsg:/dev/kmsg
    security_opt:
      - no-new-privileges:true
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /sys/fs/cgroup:/cgroup:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - prometheus
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        fluentd-async: "true"
```

And cadvisor still consumes the exact same amount of CPU (~14% for 18 containers).

![Screenshot from 2021-04-19 00-20-39](https://user-images.githubusercontent.com/998703/115162682-2a05c000-a0a5-11eb-9599-e026cd269092.png)

**Comment by zsimic** [comment]
I'm observing the same thing: no matter what I do, cadvisor uses ~10-15% CPU, all the time. Confirmed with `htop`.
This is on a raspberry-pi (if it helps).

Tried all suggestions here, including double `--` and single `-` for options... the doc mentions 2 dashes: https://github.com/google/cadvisor/blob/master/docs/runtime_options.md but this thread seems to say it should be one...

**Comment by zsimic** [comment]
Actually correction: turns out, everything I tried was a no-op...
Running cadvisor via docker-compose, and apparently one must `down` a container before it will pick up any changes.... (I was doing `restart`...)

Anyhow, after actually applying the configs, CPU usage goes drastically down with this: 
```
    command:
      - '-docker_only=true'
      - '-housekeeping_interval=30s'
      - '-disable_metrics=disk'
```

With that ^^, CPU usage goes to ~1.5%

The docs on this page: https://github.com/google/cadvisor/blob/master/docs/runtime_options.md are actually completely out of date, not only do they state double dash `--`, but they also have a completely wrong list of valid options for `-disable_metrics` (list is out of date).

Fun bonus: if one states an invalid `disable_metrics` value, one gets a huuuge dump of all of the `--help` message, multiple times, and one has to hunt for the actual "meaningful" error message like:
```
... prev full --help message (because docker-compose is trying to restart the thing...) ...
...
cadvisor    | invalid value "disk,process" for flag -disable_metrics: unsupported metric "process"
cadvisor    | Usage of /usr/bin/cadvisor:                                                                                                                                                               cadvisor    |   -allow_dynamic_housekeeping                                                                                                                                                             cadvisor    |           Whether to allow ...
... 8< ...
... tons of non-helpful output
```

**Comment by paaacman** [comment]
@zsimic about docker-compose (not related to cadvisor, but if it can help): 
You can try `docker-compose up -d --force-recreate` or `docker-compose up -d --force-recreate --build`, it's generally what I do.

**Comment by zsimic** [comment]
Awesome tip thank you! Didn't know that, will make sure to use `--force-recreate`

**Comment by iwankgb** [comment]
@zsimic [metrics disabled by default](https://github.com/google/cadvisor/blob/bfe982b346633ca5e87021019e9e2ab75aa0d7fe/cmd/cadvisor.go#L83) do not include IO, indeed. 
I would blame `housekeeping_interval` - [its default value is 1 second](https://github.com/google/cadvisor/blob/bfe982b346633ca5e87021019e9e2ab75aa0d7fe/manager/container.go#L49). The value has been set to 1 second for 7 years and on one hand I expect everybody to set it on command line but on the other - I would prefer not to break someone's metrics by changing default value.

**Comment by jorgeancal** [comment]
We had this problem at Crunch Accounting for a really long time and we found a solution for it. 

We are using [this Helm chart](https://hub.kubeapps.com/charts/ckotzbauer/cadvisor) and this is the config that we are using at the moment:

```yaml
image:
  repository: gcr.io/cadvisor/cadvisor
  tag: v0.37.5
  pullPolicy: IfNotPresent
container:
  port: 8080

  additionalArgs:
    - --housekeeping_interval=30s    # kubernetes default args
    - --max_housekeeping_interval=35s
    - --event_storage_event_limit=default=0
    - --event_storage_age_limit=default=0
    - --store_container_labels=false
    - --whitelisted_container_labels=io.kubernetes.container.name,io.kubernetes.pod.name,io.kubernetes.pod.namespace
    - --global_housekeeping_interval=30s
    - --event_storage_event_limit=default=0
    - --event_storage_age_limit=default=0
    - --disable_metrics=percpu,process,sched,tcp,udp,diskIO,disk,network      # enable only cpu, memory
    - --docker_only          # only show stats for docker containers
    - --allow_dynamic_housekeeping=true
    - --storage_duration=1m0s
```

here are some graphs showing how CPU usage has improved

![image](https://user-images.githubusercontent.com/11544239/117993074-5248ad80-b337-11eb-8ab4-d630bc3e11ca.png)

![image](https://user-images.githubusercontent.com/11544239/117993110-596fbb80-b337-11eb-82d6-a90310a8aa22.png)
