### ISSUE TITLE
whitelisted docker container labels not visible on prometheus

### ISSUE THREAD

**Issue by pradykaushik** [google/cadvisor#2570]
I am using prometheus to monitor container specific metrics using cadvisor as the exporter. First of all I would like to say that setting up cadvisor has been super easy (kudos to the developers!! 👍 ) and the documentation has been helpful. I am having a slight issue when it comes to exporting whitelisted container labels as prometheus labels.

The docker containers that are running on my cluster have the following labels assigned to them.
1. `task_id=<mesos task id>`
2. `task_hostname=<host on which task is running>`

I am running both prometheus and cadvisor standalone with the following configs for each of them
**Prometheus systemd file**
```
[Unit]
Description=Prometheus
Wants=network-online.target
After=network-online.target

[Service]
User=prometheus
Group=prometheus
ExecStart=/usr/local/bin/prometheus \
	--config.file /etc/prometheus/prometheus.yml \
	--storage.tsdb.path /var/lib/prometheus/ \
	--web.console.templates=/etc/prometheus/consoles \
	--web.console.libraries=/etc/prometheus/console_libraries

[Install]
WantedBy=multi-user.target
```

**Prometheus config yaml**
```yaml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['<ip>:9090']
```

**cAdvisor systemd file**
```
[Unit]
Description=cAdvisor
Wants=network-online.target
After=network-online.target docker.service

[Service]
User=cadvisor
Group=cadvisor
Type=simple
ExecStart=/usr/local/bin/cadvisor -port 9090 -store_container_labels=false -whitelisted_container_labels=electron_task_hostname,electron_task_id

[Install]
WantedBy=multi-user.target
```

Once I start running docker containers on the machine running cadvisor, I am not able to view any metric with the labels `electron_task_hostname` and `electron_task_id`.

Is there something that I'm missing here? Any insight would be much appreciated.
