### ISSUE TITLE
Not able to get container_fs_writes_total for pod or container

### ISSUE THREAD

**Issue by harche** [google/cadvisor#2641]
I am running a sample daemonset to generate some disk IO. 

```yaml
apiVersion: apps/v1 
kind: DaemonSet
metadata:
  name: debugpod
    #  namespace: debug-test
spec:
  selector:
    matchLabels:
      name: debugpod 
  template:
    metadata:
      labels:
        name: debugpod 
    spec:
      containers:
      - name: debugpod 
        image: busybox 
        imagePullPolicy: Always
        securityContext:
          privileged: true
          runAsUser: 0
        command: ['sh', '-c', 'while true; do dd if=/dev/urandom of=/usr/local/TestContainerWrite bs=4M count=1000; sleep 5; done']
        volumeMounts:
        - name: debug-volume 
          mountPath: /usr/local
      - name: debugpod2 
        image: busybox 
        imagePullPolicy: Always
        securityContext:
          privileged: true
          runAsUser: 0
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 6600']
        volumeMounts:
        - name: debug-volume 
          mountPath: /usr/local
      volumes:
      - name: debug-volume 
        hostPath:
          path: /usr/local
```

I can see that the IO is indeed getting generated on the target host,
```bash
[root@hartest2-6wdgf-worker-a-g4qfl ~]# ls -l /usr/local/TestContainerWrite 
-rw-r--r--. 1 root root 3393191936 Aug 17 08:30 /usr/local/TestContainerWrite
[root@hartest2-6wdgf-worker-a-g4qfl ~]# ls -l /usr/local/TestContainerWrite 
-rw-r--r--. 1 root root 3598712832 Aug 17 08:30 /usr/local/TestContainerWrite
[root@hartest2-6wdgf-worker-a-g4qfl ~]# ls -l /usr/local/TestContainerWrite 
-rw-r--r--. 1 root root 3762290688 Aug 17 08:30 /usr/local/TestContainerWrite
[root@hartest2-6wdgf-worker-a-g4qfl ~]# 
```

But the corresponding metric, `container_fs_writes_total` is not getting reported for containers and pod,

```bash
# curl localhost:8080/metrics | grep container_fs_writes_total | grep debugpod 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3944    0  3944    0     0   4821      0 --:--:-- --:--:-- --:--:--  4815container_fs_writes_total{container_label_alertmanager="",container_label_app="",container_label_app_kubernetes_io_component="",container_label_app_kubernetes_io_instance="",container_label_app_kubernetes_io_name="",container_label_app_kubernetes_io_version="",container_label_component="",container_label_controller_revision_hash="",container_label_dns_operator_openshift_io_daemonset_dns="",container_label_docker_registry="",container_label_ingresscontroller_operator_openshift_io_deployment_ingresscontroller="",container_label_ingresscontroller_operator_openshift_io_hash="",container_label_io_kubernetes_container_name="debugpod",container_label_io_kubernetes_pod_name="debugpod-xhvb8",container_label_io_kubernetes_pod_namespace="default",container_label_io_kubernetes_pod_uid="452c4bdf-0627-4133-b13e-8b074d7438c9",container_label_k8s_app="",container_label_marketplace_operatorSource="",container_label_name="",container_label_openshift_app="",container_label_openshift_io_component="",container_label_pod_template_generation="",container_label_pod_template_hash="",container_label_run="",container_label_statefulset_kubernetes_io_pod_name="",container_label_type="",device="/dev/mapper/coreos-luks-root-nocrypt",id="/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod452c4bdf_0627_4133_b13e_8b074d7438c9.slice/crio-c3d245a8eda564f7608fed48d7981d6e4cb43efd159f37bd9eacfde9d362ddec.scope",image="docker.io/library/busybox:latest",name="k8s_debugpod_debugpod-xhvb8_default_452c4bdf-0627-4133-b13e-8b074d7438c9_0"} 0 1597651490684
container_fs_writes_total{container_label_alertmanager="",container_label_app="",container_label_app_kubernetes_io_component="",container_label_app_kubernetes_io_instance="",container_label_app_kubernetes_io_name="",container_label_app_kubernetes_io_version="",container_label_component="",container_label_controller_revision_hash="",container_label_dns_operator_openshift_io_daemonset_dns="",container_label_docker_registry="",container_label_ingresscontroller_operator_openshift_io_deployment_ingresscontroller="",container_label_ingresscontroller_operator_openshift_io_hash="",container_label_io_kubernetes_container_name="debugpod2",container_label_io_kubernetes_pod_name="debugpod-xhvb8",container_label_io_kubernetes_pod_namespace="default",container_label_io_kubernetes_pod_uid="452c4bdf-0627-4133-b13e-8b074d7438c9",container_label_k8s_app="",container_label_marketplace_operatorSource="",container_label_name="",container_label_openshift_app="",container_label_openshift_io_component="",container_label_pod_template_generation="",container_label_pod_template_hash="",container_label_run="",container_label_statefulset_kubernetes_io_pod_name="",container_label_type="",device="/dev/mapper/coreos-luks-root-nocrypt",id="/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod452c4bdf_0627_4133_b13e_8b074d7438c9.slice/crio-b85717312aa239dcee059be3d912f075a98321c13184e51ae9a7e7bbf65c97ad.scope",image="docker.io/library/busybox:latest",name="k8s_debugpod2_debugpod-xhvb8_default_452c4bdf-0627-4133-b13e-8b074d7438c9_0"} 0 1597651489261
container_fs_writes_total{container_label_alertmanager="",container_label_app="",container_label_app_kubernetes_io_component="",container_label_app_kubernetes_io_instance="",container_label_app_kubernetes_io_name="",container_label_app_kubernetes_io_version="",container_label_component="",container_label_controller_revision_hash="558c674679",container_label_dns_operator_openshift_io_daemonset_dns="",container_label_docker_registry="",container_label_ingresscontroller_operator_openshift_io_deployment_ingresscontroller="",container_label_ingresscontroller_operator_openshift_io_hash="",container_label_io_kubernetes_container_name="POD",container_label_io_kubernetes_pod_name="debugpod-xhvb8",container_label_io_kubernetes_pod_namespace="default",container_label_io_kubernetes_pod_uid="452c4bdf-0627-4133-b13e-8b074d7438c9",container_label_k8s_app="",container_label_marketplace_operatorSource="",container_label_name="debugpod",container_label_openshift_app="",container_label_openshift_io_component="",container_label_pod_template_generation="1",container_label_pod_template_hash="",container_label_run="",container_label_statefulset_kubernetes_io_pod_name="",container_label_type="",device="/dev/mapper/coreos-luks-root-nocrypt",id="/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod452c4bdf_0627_4133_b13e_8b074d7438c9.slice/crio-6e439bc6313aae80b49794ae9ab305a9eaecf6f0b03e35fc0b00a48895799610.scope",image="quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:636ba95d1f2717a876ab2cb1b09ac9b40739db00d26b5cdb9c3a7d6114b75494",name="k8s_POD_debugpod-xhvb8_default_452c4bdf-0627-4133-b13e-8b074d7438c9_0"} 0 1597651489768
100 14.4M    0 14.4M    0     0  14.8M      0 --:--:-- --:--:-- --:--:-- 14.8M
```
