### ISSUE TITLE
Can I change the collect interval

### ISSUE THREAD

**Issue by wsfy15** [google/cadvisor#2660]
I'm using Cadvior on k8s, with influxdb as database. But I found some metrics were collected at irregular intervals.
```
> precision s
> select time,pod,value from container_cpu_usage_seconds_total where container='cpu' group by pod order by desc limit 5;
name: container_cpu_usage_seconds_total
tags: pod=cpu-deployment-575cfd4559-rkjsv
time       pod                             value
----       ---                             -----
1599447070 cpu-deployment-575cfd4559-rkjsv 0.178186635
1599447048 cpu-deployment-575cfd4559-rkjsv 0.178186635
1599447037 cpu-deployment-575cfd4559-rkjsv 0.178186635
1599447013 cpu-deployment-575cfd4559-rkjsv 0.17815664
1599446994 cpu-deployment-575cfd4559-rkjsv 0.17815664
```

Pod cpu-deployment-575cfd4559-rkjsv has only one container 'cpu'. The interval between each data point is different, range from 10s to 30s.  

But When I use cadvisor with only docker, not k8s, the container metrics are collected at regular intervals.

Why is this? Can I change this? Thanks!

**Comment by katarzyna-z** [comment]
Maybe [this](https://github.com/google/cadvisor/blob/master/docs/runtime_options.md#housekeeping) will be helpful for you

**Comment by wsfy15** [comment]
@katarzyna-z Thanks for your reply!
I add `--housekeeping-interval=1s` to `KUBELET_EXTRA_ARGS` for each node and restart kubelet. Now the interval betwwen collecting metrics is smaller, but still irregular, range from 4s ~ 20s. Is this related to machine performance, or any other factors?

```
> select time,pod,value from container_cpu_usage_seconds_total where container='cpu' group by pod order by desc limit 10;
name: container_cpu_usage_seconds_total
tags: pod=cpu-deployment-575cfd4559-rkjsv
time       pod                             value
----       ---                             -----
1599491557 cpu-deployment-575cfd4559-rkjsv 0.207792232
1599491553 cpu-deployment-575cfd4559-rkjsv 0.207792232
1599491549 cpu-deployment-575cfd4559-rkjsv 0.207792232
1599491535 cpu-deployment-575cfd4559-rkjsv 0.20776936
1599491529 cpu-deployment-575cfd4559-rkjsv 0.20776936
1599491523 cpu-deployment-575cfd4559-rkjsv 0.20776936
1599491503 cpu-deployment-575cfd4559-rkjsv 0.20776936
1599491490 cpu-deployment-575cfd4559-rkjsv 0.20776936
1599491484 cpu-deployment-575cfd4559-rkjsv 0.20776936
1599491468 cpu-deployment-575cfd4559-rkjsv 0.207713135
```

And I had follow [this](https://github.com/google/cadvisor/tree/master/deploy/kubernetes) to deploy cadvisor as daemonset for my k8s cluster,  and it collect metrics at regular intervals.

**Comment by katarzyna-z** [comment]
You can try to set `--allow_dynamic_housekeeping=false` , if you use cAdvisor args from [here](https://github.com/google/cadvisor/blob/master/deploy/kubernetes/overlays/examples/cadvisor-args.yaml#L16) you can also remove or modify `--max_housekeeping_interval=15s`.

If you think that the issue is caused by machine performance you can try to disable some metrics using `--disable_metrics ` parameter, see:
```
  -disable_metrics metrics
        comma-separated list of metrics to be disabled. Options are 'accelerator', 'cpu_topology','disk', 'diskIO', 'memory_numa', 'network', 'tcp', 'udp', 'percpu', 'sched', 'process', 'hugetlb', 'referenced_memory', 'resctrl'. (default memory_numa,tcp,sched,process,resctrl,udp,advtcp,hugetlb,referenced_memory,cpu_topology)
```

**Comment by wsfy15** [comment]
@katarzyna-z The `allow_dynamic_housekeeping` parameter is not list in [kubelet's command line arguments](https://kubernetes.io/zh/docs/reference/command-line-tools-reference/kubelet/). So after I add `--allow_dynamic_housekeeping=false` to `KUBELET_EXTRA_ARGS`, it failed to start kubelet.
```
Sep 08 08:30:32 master kubelet[1477]: F0908 08:30:32.814230    1477 server.go:157]  unknown flag: --allow_dynamic_housekeeping
```
How can I pass this parameter into cadvisor inside kubelet?

**Comment by dashpole** [comment]
--housekeeping_interval should be enough to get a shorter interval.  How are you querying cAdvisor?  How often does it scrape?

**Comment by wsfy15** [comment]
The following is my Prometheus config. `Scrape_interval` and `housekeeping_interval ` are both 5s. 
```
global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s
scrape_configs:
- job_name: kubernetes-cadvisor
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: https
  kubernetes_sd_configs:
  - role: node
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
  relabel_configs:
  - separator: ;
    regex: __meta_kubernetes_node_label_(.*)
    replacement: $1
    action: labelmap
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: kubernetes.default.svc:443
    action: replace
  - source_labels: [__meta_kubernetes_node_name]
    separator: ;
    regex: (.+)
    target_label: __metrics_path__
    replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
    action: replace
```
