### ISSUE TITLE
IO metrics are not summerized correctly for the pod

### ISSUE THREAD

**Issue by harche** [google/cadvisor#2668]
`container_fs_writes_total` is not correctly summarizing the IO metrics for the pod, but reports correctly for the individual containers.

For the reference, 
```bash
[root@harpatil2-7gflm-worker-c-bpmxr /]# lsblk 
NAME                         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda                            8:0    0   128G  0 disk 
├─sda1                         8:1    0   384M  0 part /boot
├─sda2                         8:2    0   127M  0 part /boot/efi
├─sda3                         8:3    0     1M  0 part 
└─sda4                         8:4    0 127.5G  0 part 
  └─coreos-luks-root-nocrypt 253:0    0 127.5G  0 dm   /sysroot
```

For the query, `container_fs_writes_total{pod="debugpod-98czb", device="/dev/dm-0", container="debugpod"}` the metric is correctly reported by cAdvisor,
```
container_fs_writes_total{container="debugpod",device="/dev/dm-0",endpoint="https-metrics",id="/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podf7447db5_ecd5_4b77_829b_031c6ad03980.slice/crio-b1e599e14e94642eb3cc6fdbe1c36806b5e6a20a3c8f92edc6ceabb40ea33ac7.scope",image="registry.fedoraproject.org/fedora:32",instance="10.0.32.4:10250",job="kubelet",metrics_path="/metrics/cadvisor",name="k8s_debugpod_debugpod-98czb_default_f7447db5-ecd5-4b77-829b-031c6ad03980_0",namespace="default",node="harpatil2-7gflm-worker-c-bpmxr.c.openshift-gce-devel.internal",pod="debugpod-98czb",service="kubelet"}	85
```

This is in sync with what's reported in the corresponding cgroup scope of that container, 

```bash
[root@harpatil2-7gflm-worker-c-bpmxr crio-b1e599e14e94642eb3cc6fdbe1c36806b5e6a20a3c8f92edc6ceabb40ea33ac7.scope]# pwd
/sys/fs/cgroup/blkio/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podf7447db5_ecd5_4b77_829b_031c6ad03980.slice/crio-b1e599e14e94642eb3cc6fdbe1c36806b5e6a20a3c8f92edc6ceabb40ea33ac7.scope
[root@harpatil2-7gflm-worker-c-bpmxr crio-b1e599e14e94642eb3cc6fdbe1c36806b5e6a20a3c8f92edc6ceabb40ea33ac7.scope]# cat blkio.throttle.io_serviced_recursive 
8:0 Read 0
8:0 Write 646
8:0 Sync 131
8:0 Async 515
8:0 Discard 0
8:0 Total 646
253:0 Read 0
253:0 Write 85 <---- correctly picked up by cAdvisor
253:0 Sync 18
253:0 Async 67
253:0 Discard 0
253:0 Total 85
Total 731
```

But for the pod level query, `container_fs_writes_total{pod="debugpod-98czb", device="/dev/dm-0", container=""}` we get,
```
container_fs_writes_total{device="/dev/dm-0",endpoint="https-metrics",id="/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podf7447db5_ecd5_4b77_829b_031c6ad03980.slice",instance="10.0.32.4:10250",job="kubelet",metrics_path="/metrics/cadvisor",namespace="default",node="harpatil2-7gflm-worker-c-bpmxr.c.openshift-gce-devel.internal",pod="debugpod-98czb",service="kubelet"}	0
```
Which is **inconsistent** with what is actually reported by the cgroup slice for that pod,
```bash
[root@harpatil2-7gflm-worker-c-bpmxr kubepods-besteffort-podf7447db5_ecd5_4b77_829b_031c6ad03980.slice]# pwd
/sys/fs/cgroup/blkio/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podf7447db5_ecd5_4b77_829b_031c6ad03980.slice
[root@harpatil2-7gflm-worker-c-bpmxr kubepods-besteffort-podf7447db5_ecd5_4b77_829b_031c6ad03980.slice]# cat blkio.throttle.io_serviced_recursive 
8:0 Read 0
8:0 Write 646
8:0 Sync 131
8:0 Async 515
8:0 Discard 0
8:0 Total 646
253:0 Read 0
253:0 Write 85  <---- Not picked up correctly by cAdvisor :-( 
253:0 Sync 18
253:0 Async 67
253:0 Discard 0
253:0 Total 85
Total 731
```

I am using following sample workload,

```yaml
apiVersion: apps/v1 
kind: DaemonSet
metadata:
  name: debugpod
    #  namespace: debug-test
spec:
  selector:
    matchLabels:
      name: debugpod 
  template:
    metadata:
      labels:
        name: debugpod 
    spec:
      containers:
      - name: debugpod 
        image: registry.fedoraproject.org/fedora:32 
        imagePullPolicy: Always
        securityContext:
        command: ['sh', '-c', 'dd if=/dev/urandom of=/TestContainerWrite bs=100M count=5 oflag=direct && sleep inf']
      - name: debugpod2 
        image: busybox 
        imagePullPolicy: Always
        securityContext:
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep inf']
```

```bash
$ kubectl version 
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2-0-g52c56ce", GitCommit:"711c56a65d92d8a61930378670ba92e04a27ef86", GitTreeState:"clean", BuildDate:"2020-07-01T23:11:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.0-rc.2+068702d", GitCommit:"068702de7d48739e835ea41b7ca959b5252de432", GitTreeState:"clean", BuildDate:"2020-09-04T01:56:40Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"linux/amd64"}
```
