### ISSUE TITLE
container_tasks_state giving result of 0 for every element

### ISSUE THREAD

**Issue by david-bickford** [google/cadvisor#2739]
I'm trying to view the status of our Docker containers in Prometheus using cAdvisor. Every other stat seems to be working except for container_tasks_state. I'm running this on an AWS EC2 instance running Linux. Here is the version info output from cAdvisor.
`cadvisor_version_info{cadvisorRevision="65fa5b44",cadvisorVersion="v0.37.0",dockerVersion="19.03.2",instance="host:8080",job="cadvisor",kernelVersion="4.15.0-1051-aws",osVersion="Alpine Linux v3.12"}`

[This is a link to screenshots of the results I get back from the container_tasks_state query and the running containers in our EC2 instance.](https://imgur.com/a/yiKmJHp)

I'm deploying cAdvisor to our EC2 instances using Ansible instead of running a docker-compose since we have many EC2 instances. Below is the Ansible script which pulls and runs cAdvisor.

```
- name: pulling and starting cAdvisor
  become: yes
  docker_container:
    name: "cadvisor"
    detach: True
    privileged: True
    networks:
      - name: "my-net"
    image: gcr.io/cadvisor/cadvisor:v0.37.0
    command: ["--enable_load_reader=true", "--container_hints=/etc/cadvisor/container_hints.json", "--v=4", "--stderrthreshold=0", "--log_dir=/var/log", "--logtostderr=false", "
--alsologtostderr=false"]
    state: started
    restart_policy: "{{ restart_policy }}"
    env:
      NODE_ENV: "{{ NODE_ENV }}"
    volumes:
      - "{{ cert_vol }}:/opt/scribe/cert"
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    log_driver: syslog
    log_options: tag={{ service_name }}/'{{ '{{' }}.ID{{ '}}' }}'
    published_ports: 0.0.0.0:8080:8080

```

Things I've tried:
- setting `--enable_load_reader=true`
- putting both containers on the same docker network
- testing different versions of cAdvisor (I tested like 8 other versions)
