### ISSUE TITLE
Not able to run with Rancher

### ISSUE THREAD

**Issue by lucasctd** [google/cadvisor#2764]
I am trying to run it with Rancher v1.6, but it does not work.
I see it makes a request to /api/v2.0/ps/ which returns `process listing failed: invalid pid "5685": strconv.Atoi: parsing "callback": invalid syntax`.

I have deployed it using the docker-compose file below

```
version: '2'

services:
    cadvisor:
        restart: always
        image: gcr.io/cadvisor/cadvisor:v0.38.6
        privileged: true
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.cadvisor.rule=Host(`cadvisor.ssaweb.solutions`)"
            - "traefik.http.routers.cadvisor.entrypoints=web"
            - "traefik.http.routers.cadvisor.service=cadvisor"
            - "traefik.http.middlewares.cadvisor-redirect-https.redirectscheme.scheme=https"
            - "traefik.http.middlewares.auth.basicauth.users=REDACTED"
            - "traefik.http.routers.cadvisor.middlewares=cadvisor-redirect-https"
            - "traefik.http.routers.cadvisor-https.rule=Host(`cadvisor.ssaweb.solutions`)"
            - "traefik.http.routers.cadvisor-https.entrypoints=websecure"
            - "traefik.http.routers.cadvisor-https.service=cadvisor"
            - "traefik.http.routers.cadvisor-https.tls=true"
            - "traefik.http.routers.cadvisor-https.tls.certresolver=le"
            - "traefik.http.routers.cadvisor-https.middlewares=auth"
            - "traefik.http.services.cadvisor.loadbalancer.server.port=8080"
            - "traefik.http.services.cadvisor.loadbalancer.passhostheader=true"
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro
        devices: 
            - "/dev/kmsg"

networks:
    default:
        external:
            name: ingress
```

It works on WSL locally (which does not have Rancher).
