### ISSUE TITLE
/metric endpoint inaccessible - deployed using K8s manifest - v0.0.37

### ISSUE THREAD

**Issue by gr8Adakron** [google/cadvisor#2840]
I have deployed CAdvisor using k8s manifestation provided in deploy folder `kustomize build bases > kubectl create -f -`
I can see this dashboard using port forward command: 

**I am running CAdvisor on Port number 8098**

```
kubectl port-forward --namespace cadvisor $(kubectl get pod --namespace cadvisor --selector="name=cadvisor" --output jsonpath='{.items[0].metadata.name}') 8084:8098
```
<img width="1423" alt="Screenshot 2021-03-27 at 2 27 11 PM" src="https://user-images.githubusercontent.com/16715364/112715808-8d6a5b00-8f08-11eb-9d8d-807c1ca083c9.png">

And now I am trying to integrate this with Prometheus by adding scrape config to prometheus - but for that I need `http://localhost:8084/metrics` to be working. 

Which isnt working it doesnt show anything - it redirect to `http://localhost:8084/containers/`

Below I am attaching my configuration YAML:

```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: cadvisor
  name: cadvisor
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: cadvisor
  name: cadvisor
  namespace: cadvisor
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  labels:
    app: cadvisor
  name: cadvisor
spec:
  privileged: true
  hostNetwork: true
  allowedHostPaths:
  - pathPrefix: /
  - pathPrefix: /var/run
  - pathPrefix: /sys
  - pathPrefix: /var/lib/docker
  - pathPrefix: /dev/disk
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: cadvisor
  name: cadvisor
rules:
- apiGroups:
  - policy
  resourceNames:
  - cadvisor
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: cadvisor
  name: cadvisor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cadvisor
subjects:
- kind: ServiceAccount
  name: cadvisor
  namespace: cadvisor
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: docker/default
  labels:
    app: cadvisor
  name: cadvisor
  namespace: cadvisor
spec:
  selector:
    matchLabels:
      app: cadvisor
      name: cadvisor
  template:
    metadata:
      labels:
        app: cadvisor
        name: cadvisor
    spec:
      automountServiceAccountToken: false
      containers:
      - image: gcr.io/cadvisor/cadvisor:v0.37.0
        name: cadvisor
        securityContext:
          privileged: true
        args:
        - --prometheus_endpoint="/metrics"
        - --port=8098
        ports:
        - containerPort: 8098
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 2000Mi
          requests:
            cpu: 150m
            memory: 200Mi
        volumeMounts:
        - mountPath: /rootfs
          name: rootfs
          readOnly: true
        - mountPath: /var/run
          name: var-run
          readOnly: true
        - mountPath: /sys
          name: sys
          readOnly: true
        - mountPath: /var/lib/docker
          name: docker
          readOnly: true
        - mountPath: /dev/disk
          name: disk
          readOnly: true
      serviceAccountName: cadvisor
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /
        name: rootfs
      - hostPath:
          path: /var/run
        name: var-run
      - hostPath:
          path: /sys
        name: sys
      - hostPath:
          path: /var/lib/docker
        name: docker
      - hostPath:
          path: /dev/disk
        name: disk
```
Any help will be appreciated.

#### ----------------------------------------------------------------------------------------------

For example - if I run the provided docker command

```
VERSION=v0.36.0 
sudo docker run \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:ro \
  --volume=/sys:/sys:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --volume=/dev/disk/:/dev/disk:ro \
  --publish=8080:8080 \
  --detach=true \
  --name=cadvisor \
  --privileged \
  --device=/dev/kmsg \
  gcr.io/cadvisor/cadvisor:$VERSION
```
Then it work I can see `/metrics` getting displayed in browser:

<img width="1012" alt="Screenshot 2021-03-27 at 3 21 45 PM" src="https://user-images.githubusercontent.com/16715364/112717076-42ecdc80-8f10-11eb-89a1-d16160a96d4c.png">
