### ISSUE TITLE
cadvisor pod CrashLoopBackOff

### ISSUE THREAD

**Issue by gxxxh** [google/cadvisor#2852]
I deployed cadvisor daemonset to monitor disk metrics of docker. here is the definition of daemonset. 
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cadvisor
  namespace: cadvisor
  labels:
    app: cadvisor
spec:
  selector:
    matchLabels:
      name: cadvisor
  template:
    metadata:
      labels:
        name: cadvisor
    spec:
      containers:
      - name: cadvisor
        image: google/cadvisor:v0.33.0
        volumeMounts:
        - name: rootfs
          mountPath: /rootfs
          readOnly: true
        - name: var-run
          mountPath: /var/run
          readOnly: false
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: docker
          mountPath: /var/lib/docker
          readOnly: true
        - name: disk
          mountPath: /dev/disk
          readOnly: true
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        args:
          - --housekeeping_interval=10s
          - --disable_metrics=disk,percpu,hugetlb,sched,tcp,udp,advtcp
      terminationGracePeriodSeconds: 30
      volumes:
      - name: rootfs
        hostPath:
          path: /
      - name: var-run
        hostPath:
          path: /var/run
      - name: sys
        hostPath:
          path: /sys
      - name: docker
        hostPath:
          path: /var/lib/docker
      - name: disk
        hostPath:
          path: /dev/disk
```
it says that the pod is crushbackoff
```
NAME                 READY   STATUS             RESTARTS   AGE
pod/cadvisor-6wnsd   0/1     CrashLoopBackOff   3          74s
```
here is the describe result of the pod
```
(base) [root@ecs-8c0a test]# kubectl describe pod -n cadvisor cadvisor-6wnsd 
Name:         cadvisor-6wnsd
Namespace:    cadvisor
Priority:     0
Node:         ecs-8c0a/192.168.0.49
Start Time:   Mon, 26 Apr 2021 15:30:28 +0800
Labels:       controller-revision-hash=5b58bcf9d9
              name=cadvisor
              pod-template-generation=1
Annotations:  cni.projectcalico.org/podIP: 10.244.27.237/32
              cni.projectcalico.org/podIPs: 10.244.27.237/32
Status:       Running
IP:           10.244.27.237
IPs:
  IP:           10.244.27.237
Controlled By:  DaemonSet/cadvisor
Containers:
  cadvisor:
    Container ID:  docker://d86f728cad914e5223169fc0e3e99e11fc475b89ca845dcc983e46081a4f2d35
    Image:         google/cadvisor:v0.33.0
    Image ID:      docker-pullable://google/cadvisor@sha256:47f1f8c02a3acfab77e74e2ec7acc0d475adc180ddff428503a4ce63f3d6061b
    Port:          8080/TCP
    Host Port:     0/TCP
    Args:
      --housekeeping_interval=10s
      --disable_metrics=disk,percpu,hugetlb,sched,tcp,udp,advtcp
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Mon, 26 Apr 2021 15:31:59 +0800
      Finished:     Mon, 26 Apr 2021 15:31:59 +0800
    Ready:          False
    Restart Count:  4
    Environment:    <none>
    Mounts:
      /dev/disk from disk (ro)
      /rootfs from rootfs (ro)
      /sys from sys (ro)
      /var/lib/docker from docker (ro)
      /var/run from var-run (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-jknrw (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  rootfs:
    Type:          HostPath (bare host directory volume)
    Path:          /
    HostPathType:  
  var-run:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run
    HostPathType:  
  sys:
    Type:          HostPath (bare host directory volume)
    Path:          /sys
    HostPathType:  
  docker:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/docker
    HostPathType:  
  disk:
    Type:          HostPath (bare host directory volume)
    Path:          /dev/disk
    HostPathType:  
  default-token-jknrw:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-jknrw
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists
                 node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                 node.kubernetes.io/unreachable:NoExecute op=Exists
                 node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  2m8s                 default-scheduler  Successfully assigned cadvisor/cadvisor-6wnsd to ecs-8c0a
  Normal   Pulled     39s (x5 over 2m8s)   kubelet            Container image "google/cadvisor:v0.33.0" already present on machine
  Normal   Created    38s (x5 over 2m7s)   kubelet            Created container cadvisor
  Normal   Started    38s (x5 over 2m7s)   kubelet            Started container cadvisor
  Warning  BackOff    37s (x10 over 2m6s)  kubelet            Back-off restarting failed container
```
when i only disable disk metircs, it works well, and I don't understand it. 
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cadvisor
  namespace: cadvisor
  labels:
    app: cadvisor
spec:
  selector:
    matchLabels:
      name: cadvisor
  template:
    metadata:
      labels:
        name: cadvisor
    spec:
      containers:
      - name: cadvisor
        image: google/cadvisor:v0.33.0
        volumeMounts:
        - name: rootfs
          mountPath: /rootfs
          readOnly: true
        - name: var-run
          mountPath: /var/run
          readOnly: false
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: docker
          mountPath: /var/lib/docker
          readOnly: true
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        args:
          - --housekeeping_interval=10s
          - --disable_metrics=disk
      terminationGracePeriodSeconds: 30
      volumes:
      - name: rootfs
        hostPath:
          path: /
      - name: var-run
        hostPath:
          path: /var/run
      - name: sys
        hostPath:
          path: /sys
      - name: docker
        hostPath:
          path: /var/lib/docker
```
