### ISSUE TITLE
takes up a lot of RAM

### ISSUE THREAD

**Issue by jboesh** [google/cadvisor#2894]
Hey
I recently started using Cadvisor in combination with prometheus in Docker images, this works well, however I see that Cadvisor takes up a lot of RAM. probably because it has to monitor a lot of docker images (65 at the moment) and collect and forward information about them..
is there any suggestion how i can reduce this? is there maybe an environment variable i can use or a setting?

my docker compose looks like this ( excluded prometheus en grafana. but I can share this part also if needed)
```
   cadvisor:
     image: google/cadvisor
     network:
       - internal
     hostname: cadvisor
     volume:
       - /:/rootfs:ro
       - /var/run:/var/run:rw
       - /sys:/sys:ro
       - /var/lib/docker:/var/lib/docker:ro
       - /cgroup:/cgroup:ro
     deploy:
       tags:
         - org.label-schema.group=monitoring
```
