### ISSUE TITLE
it should list "docker" as a subcontainer

### ISSUE THREAD

**Issue by docteurklein** [google/cadvisor#301]
Hey there,

Thanks for making container metrics graphs so easy!

The subcontainers list consists of only `system.slice` and `user.slice`, while **I expect `docker` to be listed too**.

Inside the `system.slice` (huge) list, I have some "docker-" prefixed .scope files.
- I click on one one of those scope files (http://localhost:8080/containers/system.slice/docker-3[....]6c.scope)
- I click on the last link of the breadcrumb (http://localhost:8080/containers/docker/buzzlink_db_1)

http://localhost:8080/containers/docker displays:

```
Failed to get container "/docker/" with error: unknown container "/docker/"
```

I'm using archlinux with systemd.

I run docker using fig (but it's the same with the raw docker run command):

``` yaml
cadvisor:
    image: google/cadvisor:latest
    volumes:
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
    ports:
        - 8080:8080
```
