### ISSUE TITLE
'Race condition' and 'failed to fetch hugetlb info' errors in Raspbian

### ISSUE THREAD

**Issue by eruizc-dev** [google/cadvisor#3011]
# Issue

I recently installed cadvisor in my Raspberry PI 4 and I'm missing a lot of information as you can see in the picture there's only total utilization and no container cpu utilization

![image](https://user-images.githubusercontent.com/58179604/141207025-1d8d9fb5-9470-449c-b7a9-4286a30ca87a.png)

## Logs

Because these errors repeat, I've captured one block of each:

This appears when I start cadvisor:
```
W1110 22:35:26.609580       1 manager.go:159] Cannot detect current cgroup on cgroup v2
W1110 22:35:26.812939       1 sysinfo.go:203] Nodes topology is not available, providing CPU topology
W1110 22:35:26.814874       1 machine.go:65] Cannot read vendor id correctly, set empty.
```

As soon as I make a request to `/metrics` this sometimes happens:

```
W1110 22:35:26.893795       1 container.go:590] Failed to update stats for container "/system.slice/docker-3086e71b86c9b173080be4daa80eb2e53aa
31e0a04c16742f58ca6226f6173d4.scope": error while statting cgroup v2: [open /sys/kernel/mm/hugepages: no such file or directory
failed to fetch hugetlb info
github.com/opencontainers/runc/libcontainer/cgroups/fs2.statHugeTlb
        /go/pkg/mod/github.com/opencontainers/runc@v1.0.2/libcontainer/cgroups/fs2/hugetlb.go:35
github.com/opencontainers/runc/libcontainer/cgroups/fs2.(*manager).GetStats
        /go/pkg/mod/github.com/opencontainers/runc@v1.0.2/libcontainer/cgroups/fs2/fs2.go:123
github.com/google/cadvisor/container/libcontainer.(*Handler).GetStats
        /go/src/github.com/google/cadvisor/container/libcontainer/handler.go:86
github.com/google/cadvisor/container/docker.(*dockerContainerHandler).GetStats
        /go/src/github.com/google/cadvisor/container/docker/handler.go:461
github.com/google/cadvisor/manager.(*containerData).updateStats
        /go/src/github.com/google/cadvisor/manager/container.go:641
github.com/google/cadvisor/manager.(*containerData).housekeepingTick
        /go/src/github.com/google/cadvisor/manager/container.go:587
github.com/google/cadvisor/manager.(*containerData).housekeeping
        /go/src/github.com/google/cadvisor/manager/container.go:535
runtime.goexit
        /usr/local/go/src/runtime/asm_arm64.s:1133], continuing to push stats
```

This always happens when making a request to `/metrics`:
```
W1110 22:39:44.541926       1 manager.go:700] Error getting data for container /system.slice/docker-9f77444cc2629dc8585e1b7b1dcd663c0e3231740c 3efdae60081e4a0d175b56.scope because of race condition
W1110 22:39:44.542551       1 manager.go:700] Error getting data for container /system.slice/docker-01bcff2990c2703ad658b5d9c5eef4f8472920e842 972c427f2dae0561a3691e.scope because of race condition
W1110 22:39:44.543157       1 manager.go:700] Error getting data for container /system.slice/docker-3086e71b86c9b173080be4daa80eb2e53aa31e0a04 c16742f58ca6226f6173d4.scope because of race condition
W1110 22:39:44.543800       1 manager.go:700] Error getting data for container /system.slice/docker-b205f0c2e2f88dcfa2d7aa0894b6e71be86e0329a6 0a4b1778a1471365652359.scope because of race condition
W1110 22:39:54.540484       1 manager.go:700] Error getting data for container /system.slice/docker-01bcff2990c2703ad658b5d9c5eef4f8472920e842 972c427f2dae0561a3691e.scope because of race condition
W1110 22:39:54.541070       1 manager.go:700] Error getting data for container /system.slice/docker-aaf8d325732e94d9ca421fff8bc998c872bdad0501 99668b76513979987a50e7.scope because of race condition
W1110 22:39:54.541706       1 manager.go:700] Error getting data for container /system.slice/docker-3bee7fac20c7493b8cb8107176fd628b2870d2c301 cffa278a313e31c676a3d8.scope because of race condition
W1110 22:39:54.542241       1 manager.go:700] Error getting data for container /system.slice/docker-b205f0c2e2f88dcfa2d7aa0894b6e71be86e0329a6 0a4b1778a1471365652359.scope because of race condition
W1110 22:39:54.542804       1 manager.go:700] Error getting data for container /system.slice/docker-456dd9aeef0278b927dec8e72b18f40ee404c950d1 6479fb7f99c663f02bb18b.scope because of race condition
```

## System info

OS: Raspbian Lite arm64v8
Hardware: Raspberry Pi 4B 8GB

I'm running cadvisor inside a docker container that I built for arm64v8

This is my `Dockerfile`:

```Dockerfile
FROM arm64v8/golang as build
RUN apt update && apt install -y git dmsetup
RUN git clone \
        --depth 1 \
        https://github.com/google/cadvisor.git \
        /go/src/github.com/google/cadvisor
WORKDIR /go/src/github.com/google/cadvisor
RUN make build

FROM arm64v8/debian
COPY --from=build /go/src/github.com/google/cadvisor/cadvisor /usr/bin/cadvisor
EXPOSE 8080
ENTRYPOINT ["/usr/bin/cadvisor", "-logtostderr"]
```

This is my `docker-compose.yml`:

```yml
version: '3.1'

services:
  # Many services
  cadvisor:
    image: cadvisor
    container_name: cadvisor
    command: --raw_cgroup_prefix_whitelist=/docker/
    build:
      context: cadvisor
    privileged: true
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:ro'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
      - '/dev/disk/:/dev/disk:ro'
    devices:
      - '/dev/kmsg:/dev/kmsg'
    restart: unless-stopped
```

This is the output of `docker info`:

```yml
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)

Server:
 Containers: 7
  Running: 7
  Paused: 0
  Stopped: 0
 Images: 19
 Server Version: 20.10.10
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.63-v8+
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.63GiB
 Name: homelab
 ID: AXKP:4RAO:NGGG:BSDO:SKO7:MXZV:DQSU:PEJH:QCPI:LCMX:FFZM:M2ZM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by frittenlab** [comment]
The kernel in Raspberry OS is built without hugepages support. cadvisor still worked for me until I upgrade to the new Raspberry OS based on Debian Bullseye yesterday. I was able to get it working after I downgrade the cadvisor version. I was using the prerelease version v0.43.0. Downgrading to v0.39.x or earlier seems to work. I am still seeing this error 

```
Cannot read smaps files for any PID from CONTAINER
```

in the logs. I also disable the metrics for hugetlb in my compose file with:

```
command:
  - '--disable_metrics=hugetlb'
```

Prometheus is able to scrape the cadvisor metrics again now.

**Comment by eruizc-dev** [comment]
Thanks @frittenlab, afte downgrading to 0.38 and adding `--disable_metrics=hugetlb` cadvisor finally works, but I'm seeing the same error as you regarding smaps (4 times per second)

I'll leave this issue open since downgrading is just a workaround.

For doc purposes here are my updated Dockerfile and docker-compose.

```Dockerfile
FROM arm64v8/golang as build
RUN apt update && apt install -y git dmsetup
RUN git clone \
        --branch release-v0.38 \
        --depth 1 \
        https://github.com/google/cadvisor.git \
        /go/src/github.com/google/cadvisor
WORKDIR /go/src/github.com/google/cadvisor
RUN make build

FROM arm64v8/debian
COPY --from=build /go/src/github.com/google/cadvisor/cadvisor /usr/bin/cadvisor
EXPOSE 8080
ENTRYPOINT ["/usr/bin/cadvisor", "-logtostderr"]
```

```yml
version: '3.1'

services:
  # Many services
  cadvisor:
    image: cadvisor
    container_name: cadvisor
    command: --raw_cgroup_prefix_whitelist=/docker/ --disable_metrics=hugetlb
    build:
      context: cadvisor
    privileged: true
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:ro'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
      - '/dev/disk/:/dev/disk:ro'
    devices:
      - '/dev/kmsg:/dev/kmsg'
    restart: unless-stopped
```
