### ISSUE TITLE
Missing process metrics in cgroup v2 

### ISSUE THREAD

**Issue by ysksuzuki** [google/cadvisor#3026]
We are running cadvisor in our k8s cluster following the example setup, but process metrics such as container_sockets and container_processes are missing.  Our node's OS is [Flatcar 2983.2.1](https://www.flatcar-linux.org/releases/#release-2983.2.1) and it has already migrated to the cgroup V2 from version 2969.0.0. 

I investigated cadvisor code and found out that cadvisor didn't call processStatsFromProcs because it tried to get CPU subsystem path and use it but there's no such pash in cgroup v2. I think cadvisor needs to use the unified cgroup path in cgroup v2 environment.
https://github.com/google/cadvisor/blob/v0.43.0/container/libcontainer/handler.go#L173

cAdvisor v0.43.0
Node OS: Flatcar 2983.2.1
Container runtime: containerd 1.5.6

Manifest
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: docker/default
  labels:
    app: cadvisor
  name: cadvisor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: cadvisor
      name: cadvisor
  template:
    metadata:
      labels:
        app: cadvisor
        name: cadvisor
    spec:
      automountServiceAccountToken: false
      containers:
      - args:
        - --housekeeping_interval=10s
        - --max_housekeeping_interval=15s
        - --event_storage_event_limit=default=0
        - --event_storage_age_limit=default=0
        - --enable_metrics=app,cpu,cpuLoad,disk,diskIO,memory,network,process
        - --containerd=/var/run/k8s-containerd.sock
        - --store_container_labels=false
        - --whitelisted_container_labels=io.kubernetes.container.name,io.kubernetes.pod.name,io.kubernetes.pod.namespace
        image: quay.io/cybozu/cadvisor:0.43.0.1
        name: cadvisor
        ports:
        - containerPort: 8080
          hostPort: 9110
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 800m
            memory: 2000Mi
          requests:
            cpu: 400m
            memory: 400Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /rootfs
          name: rootfs
          readOnly: true
        - mountPath: /var/run
          name: var-run
          readOnly: true
        - mountPath: /sys
          name: sys
          readOnly: true
        - mountPath: /var/lib/docker
          name: docker
          readOnly: true
        - mountPath: /dev/disk
          name: disk
          readOnly: true
      hostPID: true
      serviceAccountName: cadvisor
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: cke.cybozu.com/role
        operator: Equal
        value: storage
      volumes:
      - hostPath:
          path: /
        name: rootfs
      - hostPath:
          path: /var/run
        name: var-run
      - hostPath:
          path: /sys
        name: sys
      - hostPath:
          path: /var/lib/docker
        name: docker
      - hostPath:
          path: /dev/disk
        name: disk
```
