### ISSUE TITLE
Permission error trying to use gcr.io/cadvisor/cadvisor:latest

### ISSUE THREAD

**Issue by benbro** [google/cadvisor#3032]
When creating a container based on gcr.io/cadvisor/cadvisor:latest I'm getting an error:
```
Your client does not have permission to get URL <code>/v2/cadvisor/cadvisor/manifests/latest</code> from this server
```

**Comment by leni8ec** [comment]
Same here with

```
version: '3.4'

services:
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.46.0
```

```
That’s an error. 
Your client does not have permission to get URL '/v2/cadvisor/cadvisor/manifests/v0.47.0' from this server. 
That’s all we know.
```
