### ISSUE TITLE
cgroup error

### ISSUE THREAD

**Issue by Altycoder** [google/cadvisor#3073]
I'm running in docker on top of an Arch host (LTS kernel 5.15.25)

docker compose:

```
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    ports:
      - 8089:8089
```

I get the following error:

`1 manager.go:159] Cannot detect current cgroup on cgroup v2`

There's nothing to connect to on port 8089 (I have another service using 8088).

**Comment by varac** [comment]
Same, I got this after upgrading from Debian buster to bullseye, with cadvisor debian package `0.38.7+ds1-2+b7`.

**Comment by MikeSpreitzer** [comment]
I got this too, and was also alarmed.  So I used the source.  https://github.com/google/cadvisor/blob/24e7a9883d12f944fd4403861707f4bafcaf4f3d/manager/manager.go#L159 .  Turns out, this is a badly worded message.  It is not saying there is something wrong with my system; it is reporting a limitation of the software.

**Comment by mqu** [comment]
me too, on debian/bullseye + dockerized cadvisor.

**Comment by thiagocpv** [comment]
me too, same environment. (debian bullsyey + dockerized cadvisor).

**Comment by FullStackIndie** [comment]
I am also getting this error after upgrading from Ubuntu 20.04 Focal Fossil to 22.04 Jammy Jellyfish with a dockerized Cadvisor

**Comment by AndresCdo** [comment]
Running Docker Engine on Ubuntu 22.04.1 LTS:

- Image _gcr.io/cadvisor/cadvisor_:

`W0925 01:06:42.578456       1 manager.go:159] Cannot detect current cgroup on cgroup v2`
`E0925 01:06:47.642679       1 info.go:114] Failed to get system UUID: open /etc/machine-id: no such file or directory`
`W0925 01:06:47.647046       1 manager.go:288] Could not configure a source for OOM detection, disabling OOM events: open /dev/kmsg: no such file or directory`

**Comment by stepanof** [comment]
I have the same problem on "22.04.1 LTS (Jammy Jellyfish)". 
I'm using image "`gcr.io/cadvisor/cadvisor`"

**Comment by JPFreeski** [comment]
Is this the reason why I can't see my containers properly in grafana?

**Comment by komkomissarov** [comment]
```
monitoring_cadvisor | W1014 10:46:43.273292       1 manager.go:159] Cannot detect current cgroup on cgroup v2
monitoring_cadvisor | W1014 10:46:43.380525       1 manager.go:288] Could not configure a source for OOM detection, disabling OOM events: open /dev/kmsg: no such file or directory
```
Ubuntu 22.04 
docker-compose version 1.29.2, build unknown
Docker version 20.10.16, build aa7e414

**container_memory_rss** showing zero, but **container_cpu_usage_seconds_total** extracted normally. 

docker-compose file 
```
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: monitoring_cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    ports:
      - 8080:8080
```

No such problem on Ubuntu 18 or 20.
