### ISSUE TITLE
Needs a way to filter out network interfaces for which we dont need stats

### ISSUE THREAD

**Issue by sandipb** [google/cadvisor#3096]
In Kubernetes clusters, or perhaps other implementations as well, all host net based containers are emitting `container_network_*`  metrics for all `calixxx` calico interfaces which are visible to them.

Each calico interface is emitting about 96 metrics, and there is one interface for every non-host-net pod. This is a lot of metrics which are not needed. And really significant for large clusters - in our medium sized 100 node cluster, this was about 0.5 million metrics, which we had to drop in prometheus using `metric_relabel_configs`:

```yaml
    metric_relabel_configs:
...
      - source_labels: ['__name__','interface']
        regex: container_network_[^;]*;cali.+
        action: drop
```

Perhaps a command line filter can ignore interfaces based on a pattern? like `--ignore-net-dev=^cali.+`
