### ISSUE TITLE
Memory usage showing zero

### ISSUE THREAD

**Issue by martinjgrunwald** [google/cadvisor#3115]
This is the Compose stack I use on 2 different machines:

```
cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8081:8080
    restart: unless-stopped
```

One machine is an Ubuntu 20.04 LTS, the other is an Ubuntu 22.04 LTS
On the 20.04 everything works just fine
On the 22.04 memory usage is apparently zero (which it isn't, I run a few containers)

The only difference I could find was in the WebUI. Under Subcontainers a directory named /init.scope is listed on the 22.04 machine.
On the 20.04 machine this entry is missing and instead it says /docker where I can find all the memory info broken down per container. This is the information I am missing on my other machine.
