### ISSUE TITLE
ZFS Watcher Error

### ISSUE THREAD

**Issue by norsemanGrey** [google/cadvisor#3123]
I am using ZFS as storage driver for Docker. Even though I have disabled "disk" metrics (using --disable_metrics) I continuously get the following errors in the Docker log:

```
E0530 13:38:48.432743       1 watcher.go:98] encountered error getting zfs filesystem: fastpool-1/appdata/docker/datasets: exit status 1: "/usr/sbin/zfs fs list -Hp -o name,origin,used,available,mountpoint,compression,type,volsize,quota,referenced,written,logicalused,usedbydataset fastpool-1/appdata/docker/datasets" => Failed to initialize the libzfs library.
E0530 13:38:48.432934       1 watcher.go:63] encountered error refreshing zfs watcher: exit status 1: "/usr/sbin/zfs fs list -Hp -o name,origin,used,available,mountpoint,compression,type,volsize,quota,referenced,written,logicalused,usedbydataset fastpool-1/appdata/docker/datasets" => Failed to initialize the libzfs library.
```

This is my compose file:

```
  metrics-scraper:

    image: gcr.io/cadvisor/cadvisor:latest

    container_name: metrics-scraper

    hostname: cadvisor

    security_opt:

      - no-new-privileges:true

    command:

      - '--docker_only=true'
      - '--housekeeping_interval=30s'
      - '--disable_metrics=accelerator,hugetlb,resctrl,disk,diskIO,tcp,udp,sched,process,memory_numa,referenced_memory,advtcp'

    devices:

      - /dev/kmsg:/dev/kmsg

    networks:

      monitoring-net:
      
        ipv4_address: ${IP_MONITORING_BASE}.${ID_METRICS_SCRAPER}

    ports:

      - target: 8080
        published: ${PORT_EXTERNAL_BASE}${ID_METRICS_SCRAPER}


    volumes:

      - type: bind
        source: /var/run
        target: /var/run
        read_only: true

      - type: bind
        source: /var/lib/docker
        target: /var/lib/docker
        read_only: true         

      - type: bind
        source: /
        target: /rootfs
        read_only: true

      - type: bind
        source: /sys
        target: /sys
        read_only: true        

      - type: bind
        source: /dev/disk
        target: /dev/disk
        read_only: true      

      - type: bind
        source: /dev/zfs
        target: /dev/zfs
        read_only: true         

    restart: unless-stopped
```
