### ISSUE TITLE
Cannot get cadvisor to work getting error Failed to create a Container Manager: mountpoint for cpu not found

### ISSUE THREAD

**Issue by sanfx** [google/cadvisor#3170]
Here is my docker compose file
```

  cadvisor:
    image: google/cadvisor
    networks:
      - {{traefik_network_name}}
    command: -logtostderr -docker_only
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    mem_limit: 512m
    mem_reservation: 128M
```
when run the command `docker-compose up`  I get below error and finally container exiits.

```
Creating exporter_cadvisor_1 ... done
Attaching to exporter_dockerd-exporter_1, exporter_cadvisor_1
dockerd-exporter_1  | 2022/09/16 21:30:17 socat[1] N listening on AF=2 0.0.0.0:9323
cadvisor_1          | F0916 21:34:45.765200       1 cadvisor.go:146] Failed to create a Container Manager: mountpoint for cpu not found
cadvisor_1          | F0916 21:34:47.445051       1 cadvisor.go:146] Failed to create a Container Manager: mountpoint for cpu not found
exporter_cadvisor_1 exited with code 255
cadvisor_1          | F0916 21:34:49.103546       1 cadvisor.go:146] Failed to create a Container Manager: mountpoint for cpu not found
exporter_cadvisor_1 exited with code 255
cadvisor_1          | F0916 21:34:50.890670       1 cadvisor.go:146] Failed to create a Container Manager: mountpoint for cpu not found
exporter_cadvisor_1 exited with code 255
cadvisor_1          | F0916 21:34:53.062030       1 cadvisor.go:146] Failed to create a Container Manager: mountpoint for cpu not found
exporter_cadvisor_1 exited with code 255
cadvisor_1          | F0916 21:34:56.029132       1 cadvisor.go:146] Failed to create a Container Manager: mountpoint for cpu not found
exporter_cadvisor_1 exited with code 255
cadvisor_1          | F0916 21:35:00.634196       1 cadvisor.go:146] Failed to create a Container Manager: mountpoint for cpu not found
exporter_cadvisor_1 exited with code 255

```
