### ISSUE TITLE
How to disable this WARN `machine_libipmctl.go:64] There are no NVM devices!`

### ISSUE THREAD

**Issue by zawadaa** [google/cadvisor#3198]
My environment is a virtual machine without NVM device
I start cAdvisor like that:

```
docker run   --volume=/:/rootfs:ro   --volume=/var/run:/var/run:ro   --volume=/sys:/sys:ro   --volume=/var/lib/docker/:/var/lib/docker:ro   --volume=/dev/disk/:/dev/disk:ro   --publish=8080:8080   --detach=true   --name=cadvisor   --privileged   --device=/dev/kmsg   --restart=unless-stopped  gcr.io/cadvisor/cadvisor:v0.46.0
```

Periodically in the logs appears: 
>W1114 11:03:35.331845       1 machine_libipmctl.go:64] There are no NVM devices!

How to disable this message?

**Comment by abraxaswd** [comment]
Looks like this issue is appearing with Ubuntu 22.04 LTS and it is not possible to start the container and get any data to prometheus.

**Comment by Creatone** [comment]
The `gcr.io/cadvisor/cadvisor:v0.46.0` image has set every build tag. It means that it is using the `nvm/machine_libipmctl.go` rather than `nvm/machine_no_libipmctl.go` file when building binary.
Unfortunately, this is the only mechanism that decides about gathering NVM-related metrics.

To avoid that warning you need to build an image without `libipmctl` flag. To achieve that you can simply edit `deploy/Dockerfile` lines 44 - 46.

```diff
-   if [ "$(uname --machine)" = "x86_64" ]; then \
-         export GO_TAGS="$GO_TAGS,libipmctl"; \
-   fi; \
```

**Comment by skupjoe** [comment]
This is also happening for me on v0.47.1 using the image directly from gcr.io/cadvisor. I don't think it should be necessary to build this image ourselves to simply ignore this!

**Comment by abraxaswd** [comment]
The problem on ubuntu was fixed after installing updates for ubuntu 22.04 LTS kernel and container.io. After that the error is still appearing but data is transfered to prometheus and grafana. I used the gcr.io/cadvisor 46.0 container image. But even after upgrading to 0.47.1 it is still working.

**Comment by zawadaa** [comment]
> I don't think it should be necessary to build this image ourselves to simply ignore this!

Totally agree! This should be done in runtime.
Like many others metrics...

**Comment by namlh-eureka** [comment]
got this error when using `gcr.io/cadvisor/cadvisor-amd64:v0.47.2` . I'm running cadvisor as docker service in swarm

```
version: '3'

services:
  cadvisor-exporter:
    image: gcr.io/cadvisor/cadvisor-amd64:v0.47.2
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring
    deploy:
      mode: global
    command:
      - "--housekeeping_interval=30s"
      - "--docker_only=true"
      - "--disable_metrics=percpu,sched,tcp,udp,disk,diskIO,hugetlb,referenced_memory,cpu_topology,resctrl"

networks:
  monitoring:
    external: true
```
