### ISSUE TITLE
container_cpu_usage_seconds_total should include the pod's uid

### ISSUE THREAD

**Issue by ntl-ibm** [google/cadvisor#3270]
**What would you like to be added**:
Metrics such as container_cpu_usage_seconds_total should include the UID of the pod.

**Why is this needed**:
My pod is part of a stateful set, so it keeps the same name when the pod is deleted and recreated. I would like to calculate CPU usage over a specific time interval.

Consider:
sum(increase(container_cpu_usage_seconds_total[<time_window>])) by (namespace, pod)

Assume that a pod was ended during the window and restarted. I want to get two time series returned.
1) CPU usage for the pod that was ended from the beginning of the time window until the end of the pod
2) CPU usage for the new pod that was started from the time the pod started until the end of the time window.

But because the aggregation is only on namespace and pod, I will get one time series with the aggregate. I need to include the pod's uid (included with the pod metrics), but this is not available.

**Describe the solution you'd like**
The "id" is almost what I need, and I think it has the pod id embedded in the path value.
For example:  `id="/system.slice/containerd.service/kubepods-burstable-pod52d49e6c_9e54_4602_842c_39b18a3b5a29.slice:cri-containerd:0c509dd847a611eb3e86fd58354a883fbfd223361ce38e2d7374aac751a69119"`

52d49e6c_9e54_4602_842c_39b18a3b5a29 looks like what I need, and I can extract it after the prometheus query. But it's inconvenient and probably doesn't perform as well.

**Additional context**
It's possible I'm missing something here, but that's what I found after looking at this for a long time.

**Comment by juliamatsak** [comment]
Any updates here?

**Comment by scaps1** [comment]
Guys, can someone give updates or workaround?

**Comment by d-uzlov** [comment]
I extract uid from `id` label using the following metric relabellings:

```yaml
  - targetLabel: uid
    sourceLabels: [ id ]
    regex: '/kubepods.slice/.*\.slice/.*-pod([0-9a-z_]*)\.slice/cri-.*'
  - targetLabel: uid
    sourceLabels: [ id ]
    regex: '/kubepods/.*/pod([0-9a-z-]*)/.*'
  - targetLabel: uid
    sourceLabels: [ uid ]
    regex: (.*)_(.*)
    replacement: '$1-$2'
  - targetLabel: uid
    sourceLabels: [ uid ]
    regex: (.*)_(.*)
    replacement: '$1-$2'
  - targetLabel: uid
    sourceLabels: [ uid ]
    regex: (.*)_(.*)
    replacement: '$1-$2'
```

However, I found a few issues with this approach in general.

First, `id` if not really an ID, it's a cgroup path. I think the format depends both on kubelet and CRI. As you can see, I have 2 regexes, and neither one will match example from the original request. I found that in my cluster different nodes had different id formats, because some had containerd version 2.0.0 and some 2.0.4.

Second, cgroup path is not guaranteed to have uid in it at all.
I found that it usually has uid for regular pods, but for static pods it seems like kubelet uses some hash instead of uid.
So this approach will not work for static pods, which naturally also always have the same pod name.
