### ISSUE TITLE
Confusing tasks determination logic in resctrl

### ISSUE THREAD

**Issue by Faione** [google/cadvisor#3334]
I'd like to enable resctrl in cadvisor to perform fine-grained monitoring of containers, but get some unexpected behaviors. 

```
E0617 06:44:48.008833   74762 collector.go:60] Failed to setup container "/docker/xxxx" resctrl collector: couldn't find monitoring group matching "/docker/xxxxx" container: group should have container pids only 
```

I read the source code and found some confusing logic: 

In `manager/manager.go` , `cont.getContainerPids()` was set as the `getContainerPids` to init resctrl manager. The method indeed does what its name suggests - it is capable of retrieving Processes from a container like `ps -e`. There is actually a bug here. When cadvisor is running inside a container, executing `ps` will create a new process and be recorded in `getContainerPids`. However, this process ends shortly afterward, which leads to the problem of there should be all pids in group.

Then first in `prepareMonitoringGroup()`, resctrl manager would use `getAllProcessThreads() to retrieve all Threads of a given PID and write them to mon group tasks.  `getContainerPids` only  retrieving Processes, but here resctrl writes Threads into tasks,  which clearly does not conform to `group should have container pids only`

Thus, everything work fine until I set `resctrl_interval`, which will periodically synchronize threads in the container with resctrl tasks. In `arePIDsInGroup` , it checks if the number of Processes in the container is equal to the tasks in the mon group. Obviously, for multi-threaded applications, this will return false.

I really want to know why it was designed this way

**Comment by iwankgb** [comment]
Regarding `ps -e` problem: if you run cAdvisor inside a container, then you may need yo use host PID namespaces and set the container to be privileged. See: https://github.com/google/cadvisor/blob/master/docs/running.md

**Comment by Faione** [comment]
Thank you for your reply , yes,  it is indeed necessary to set it up this way in order for the cAdvisor inside the container to run properly. In fact, this is what I have done, and my configuration is as follows: 

```yaml
version: '3.8'
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    network_mode: host
    pid: host
    privileged: true
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:ro'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
      - '/dev/disk/:/dev/disk:ro'
    devices:
      - '/dev/kmsg:/dev/kmsg'
    restart: unless-stopped
    command:
      - '--docker_only'
      - '--enable_metrics=advtcp,app,cpu,cpuLoad,cpu_topology,cpuset,disk,diskIO,memory,memory_numa,network,oom_event,process,referenced_memory,resctrl,sched,tcp,udp'
      - '--enable_load_reader'
      - '--resctrl_interval=10s'
      - '--port=9080'
```

But the `there should be all pids in group` problem still exists when i enabled `resctrl_interval`. 

```
E0619 01:47:32.126607   20363 collector.go:60] Failed to setup container "/docker/xxx" resctrl collector: "couldn't find control group matching container" "/docker/xxx": "there should be all pids in group"
```

When cAdvisor retrieves the process running in its own container, it executes `ps -e` which generates a **short-lived** process and is recorded in the process list. This seems fine, but when `resctrl_interval` is enabled, the resctrl collector periodically checks if the pid is in tasks. Obviously, for a **short-lived** process like `ps -e`, an error of `there should be all pids in group` will occur, even though it doesn't seem like an actual error.

For me, the task determination logic in resctrl still remains very confusing
