### ISSUE TITLE
Unable to get btrfs mountpoint IDs

### ISSUE THREAD

**Issue by sbe-arg** [google/cadvisor#3357]
Not sure whats going on here:

Running on fedora 38 any suggestions appreciated

```
Unable to get btrfs mountpoint IDs: stat failed on /dev/mapper/luks-id with error: no such file or directory
```

**Comment by emiago** [comment]
is there any workaround to  stop advisor reading this or some context arround this?

**Comment by lucagez** [comment]
Make sure `cadvisor` is running in `privileged` mode. Was facing the same issue without the flag

**Comment by simonhammes** [comment]
I'm running into the same issue on Fedora 41 (exact same error message). I'm using an encrypted BTRFS drive.

This is my docker-compose config:

```yml
services:
  # ...
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.2
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
```

@lucagez Setting `privileged: true` did not seem to help. Can you share your configuration?

**Comment by simonhammes** [comment]
I found a workaround. Disabling the `disk` and `referenced_memory` metrics seemed to help (Fedora 41, encrypted BTRFS drive):

```yml
cadvisor:
  image: gcr.io/cadvisor/cadvisor:v0.49.2
  privileged: true
  command:
    - --disable_metrics=disk,referenced_memory
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
```
