### ISSUE TITLE
Dont get GPU Metrics on Unraid

### ISSUE THREAD

**Issue by Svenum** [google/cadvisor#3374]
Here is my Compose file:
```yml
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/run:/var/run:rw
      - /var/lib/docker/:/var/lib/docker:ro
      - /usr/lib64/libnvidia-ml.so.1:/usr/lib64/libnvidia-ml.so.1:ro
    privileged: true
    environment:
      LD_LIBRARY_PATH: /usr/lib64/libnvidia-ml.so.1
    devices:
      - /dev/kmsg:/dev/kmsg
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
```
I dont get GPU Metrics. Can anybody help me?
