### ISSUE TITLE
[Question] error during container init: error mounting "/run/host-services/docker.proxy.sock" to rootfs at "/var/run/docker.sock"

### ISSUE THREAD

**Issue by aristo0922** [google/cadvisor#3388]
**I'v got this error.**
`Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/run/host-services/docker.proxy.sock" to rootfs at "/var/run/docker.sock": open /var/lib/docker/overlay2/9075e89a9ab3596fbbed46ea10ce8cd44fffd9880311e6764c0a0ba90ec5cbc4/merged/run/docker.sock: read-only file system: unknown
`

before then **i tried**
1. delete privileged: true
2. delete - /var/run/docker.sock:/var/run/docker.sock:rw
 - it worked but can not get data from backend container with this error
 `failed to get docker info: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`
3. change `/var/run/docker.sock:/var/run/docker.sock:rw` to` /var/run/docker.sock:/var/run/docker.sock:ro` and also `/var/run/docker.sock:/var/run/docker.sock`
4. add securito_opt with this repository's default.json
```
    security_opt:
      - seccomp=default.json
```

here is my **docker-compose.yml**
```
version: "3"
services:
...
  cadvisor:
#    image: zcube/cadvisor:latest # m1 칩 환경 : 호환성 문제
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /dev/disk/:/dev/disk:ro
#      - $GOPATH/src/github.com/google/cadvisor/perf/testing:/etc/configs/perf
    #      - /etc/machine-id:/etc/machine-id:ro
#      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
#      - /var/lib/dbus:/var/lib/dbus:ro
    devices:
      - /dev/kmsg:/dev/kmsg
    expose:
      - 8080
    restart: always
#    privileged: true
    depends_on:
      - prometheus
    security_opt:
      - seccomp=default.json
```

I'm trying in my labtop, m2 ventura 13.4.1, memory: 16gb.
