### ISSUE TITLE
cadvisor error getting perf_event cgroup path: could not find path for resource \perf_event\ for container

### ISSUE THREAD

**Issue by IIIdefconIII** [google/cadvisor#3436]
Keep getting this error several times on synology DSM based nas.

Would love to have some feedback so i can cure this error spamming my discord server.

Thanks alot

```
  cadvisor:
    container_name: Prometheus-cAdvisor
    image: gcr.io/cadvisor/cadvisor:latest
    restart: on-failure:5
    command:
      - '--docker_only=true'
    hostname: prometheus-cadvisor
#    networks:
#      - prometheus-net
#    mem_limit: 256m
#    mem_reservation: 64m
#    cpu_shares: 512
    security_opt:
      - no-new-privileges=true
    read_only: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ## Pullio
      org.hotio.pullio.notify: "true"
      org.hotio.pullio.update: "true"
      org.hotio.pullio.discord.webhook: JEPYUPJEP
      org.hotio.pullio.author.avatar: https://raw.githubusercontent.com/walkxcode/Dashboard-Icons/main/png/cadvisor.png
```
