### ISSUE TITLE
Memory Usage always zero

### ISSUE THREAD

**Issue by devicarus** [google/cadvisor#3469]
cAdvisor is always showing 0 memory usage

HW: `Raspberry Pi 5`
OS: `Debian 12`

My `docker-compose.yml`:
```yaml
cadvisor:
  image: gcr.io/cadvisor/cadvisor:v0.47.2
  container_name: cadvisor
  ports:
    - 8080:8080
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /dev/disk/:/dev/disk:ro
    - /etc/machine-id:/etc/machine-id:ro
  devices:
    - /dev/kmsg
  privileged: true
  restart: unless-stopped
```

Logs: [cadvisor.log](https://github.com/google/cadvisor/files/14310924/cadvisor.log)
