### ISSUE TITLE
v0.49.1 arm64 - Error while reading product_name: open /sys/class/dmi/id/product_name: no such file or directory

### ISSUE THREAD

**Issue by Chippi** [google/cadvisor#3493]
**Upon upgrading from version 47.2 to 0.49.1, the following lines are repeatedly logged every 5 minutes:**

## Errors
```
I0306 22:52:36.995727       1 sysinfo.go:303] Found cpu without cache information, cpuPath: [/sys/devices/system/cpu/cpu0 /sys/devices/system/cpu/cpu1 /sys/devices/system/cpu/cpu2 /sys/devices/system/cpu/cpu3]

I0306 22:52:36.995817       1 gce.go:44] Error while reading product_name: open /sys/class/dmi/id/product_name: no such file or directory
```

## Specs
- Raspberry PI 5, 8 GB
- Architecture: arm64
- Operating System: Debian GNU/Linux 12 (bookworm)
- Kernel: Linux 6.1.0-rpi8-rpi-2712

## Docker compose
```
version: '3.8'
services:
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor-arm64:v0.49.1
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /etc/machine-id:/etc/machine-id:ro # Fixes UUID error
    ports:
      - 8080:8080
    devices:
      - /dev/kmsg
    command:
      - '-docker_only=true'
      - '-storage_duration=1m0s'
      - '-enable_metrics=cpu,memory,diskIO'
    healthcheck:
      disable: true
```
