### ISSUE TITLE
Multiple Metrics die down in just 5 minutes

### ISSUE THREAD

**Issue by jayjoshi64** [google/cadvisor#3581]
When I start the container, all the data is collected correctly.  Slowly one by one the container start disappearing.  Within 5 minutes, all the containers are usually gone from the graphs.   

These are the counters which are affected: 
* container_cpu_usage_seconds_total
* container_network_receive_bytes_total
* container_network_transmit_bytes_total

![Aug-20-2024 22-33-42](https://github.com/user-attachments/assets/3be32d7f-b9f0-488c-b286-9d78d71b27bd)

My setup: 
* Running through docker compose in an ubuntu machine. 
* My docker compose: 
```
cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    command:
      - '-port=8098'
      - '--global_housekeeping_interval=10m0s'
      - '--housekeeping_interval=5m0s'
      - '--max_housekeeping_interval=10m0s'
    ports:
      - 8098:8098
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    networks:
      - console
    privileged: true
    restart: unless-stopped
```
