### ISSUE TITLE
cadvisor dockerfile healthchecks do not utilize correct port if --port command is used to change from default 8080

### ISSUE THREAD

**Issue by JerrettDavis** [google/cadvisor#3618]
The Dockerfile utilizes a static port `8080` for the healthcheck and expose operations:

https://github.com/google/cadvisor/blob/255cff7808a7d23802852e6fd9a12320b1035bf1/deploy/Dockerfile#L68

If a non-default port is utilized, users have to explicitly set the `CADVISORT_HEALTHCHECK_URL` environment variable to reflect the updated port otherwise the status will remain "unhealthy".

```yaml
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    command:
      - '-port=9092'
    expose:
      - 9092
    ports:
      - 9092:9092
    environment:
      - 'CADVISOR_HEALTHCHECK_URL=http://localhost:9092/healthz'
```
