### ISSUE TITLE
Is there a way for cAdvisor to collect pod custom labels?

### ISSUE THREAD

**Issue by MagicStarTrace** [google/cadvisor#3627]
```
Template:
    metadata:
      annotations:
      ...
      creationTimestamp: null
      labels:
        app: api-gateway
        app_part: default
```

cAdvisor doesn't seem to support collecting such custom metrics?

pod lable:
app=api-gateway

Is there any way to make it support it?
