### ISSUE TITLE
Missing labels : microk8s  with image: gcr.io/cadvisor/cadvisor:v0.47.0

### ISSUE THREAD

**Issue by schau87** [google/cadvisor#3687]
Here is the deployment:
```
#cat cad.yaml 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadvisor
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cadvisor
  template:
    metadata:
      labels:
        app: cadvisor
    spec:
      containers:
      - name: cadvisor
        image: gcr.io/cadvisor/cadvisor:v0.47.0
        ports:
        - containerPort: 8080
        args:
        - --housekeeping_interval=30s
        - --max_housekeeping_interval=35s
        - --event_storage_event_limit=default=0
        - --event_storage_age_limit=default=0
        - --store_container_labels=true
        - --whitelisted_container_labels=io.kubernetes.container.name,io.kubernetes.pod.name,io.kubernetes.pod.namespace,io.kubernetes.pod.uid
        - --global_housekeeping_interval=30s
        - --disable_metrics=percpu,process,sched,tcp,udp,diskIO,disk
        securityContext:
          privileged: true
        volumeMounts:
        - name: sys
          mountPath: /sys
        - name: varrun
          mountPath: /var/run
        - name: varlibdocker
          mountPath: /var/lib/docker
      volumes:
      - name: sys
        hostPath:
          path: /sys
          type: Directory
      - name: varrun
        hostPath:
          path: /var/run
          type: Directory
      - name: varlibdocker
        hostPath:
          path: /var/lib/docker
          type: Directory

```
After deploying, I tried to exec into the pod and looked for the labels and it doesn't show up:

```
root@ip-10-201-4-206:~# microk8s kubectl exec -it pod/cadvisor-75db57b79b-cwqth -c cadvisor  -- sh -c "wget -qO- http://localhost:8080/metrics" |egrep -e 'container_cpu_usage_seconds_total' -e 'container_label_io_kubernetes_pod_name'
# HELP container_cpu_usage_seconds_total Cumulative cpu time consumed in seconds.
# TYPE container_cpu_usage_seconds_total counter
container_cpu_usage_seconds_total{cpu="total",id="/"} 1024.723895 1747934308262
container_cpu_usage_seconds_total{cpu="total",id="/init.scope"} 14.189901 1747934316343
container_cpu_usage_seconds_total{cpu="total",id="/kubepods"} 232.520142 1747934298032
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/besteffort"} 22.564805 1747934288375
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/besteffort/pod1dd1b2f7-f64e-47b3-a6de-e739b51cc4e0"} 7.764063 1747934297729
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/besteffort/pod1dd1b2f7-f64e-47b3-a6de-e739b51cc4e0/047bb594c710ba56a3cc5efc1015a635a6236dde49c5b5229ff05a4fb467da95"} 0.035616 1747934280888
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/besteffort/pod1dd1b2f7-f64e-47b3-a6de-e739b51cc4e0/6a892ddc775858249fed45377e425ce29ac0c882d22f8e5603a2a14846d0ee26"} 7.715539 1747934286463
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/besteffort/pod53a90196-121b-43f3-8f11-74257ca078e4"} 1.842722 1747934290852
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/besteffort/pod53a90196-121b-43f3-8f11-74257ca078e4/73c136e54223b2bdde7622f91bf79579005f2aacd5fab3457e3d4fd1e97e03d7"} 0.043672 1747934302571
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/besteffort/pod53a90196-121b-43f3-8f11-74257ca078e4/7cfbf4ccadc83f6c7ed3049ca5a1affdcdb348566da006c60be80fd931b143d1"} 1.802597 1747934295318
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/besteffort/pod641b4c41-1e00-426b-b384-5ec06358f2a9"} 0.070421 1747934314576
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/besteffort/pod641b4c41-1e00-426b-b384-5ec06358f2a9/0c9b01671fc892ad4e53834a844aef9c0e1ece08692058298d0abf2608cae698"} 0.040551 1747934313023
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/besteffort/pod641b4c41-1e00-426b-b384-5ec06358f2a9/8e8271f8d36b11e4261cdd8fda6db5d3e4889b8c4d8edf96e9c5a1557b57a356"} 0.02987 1747934318547
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/besteffort/pod84f30457-94e4-4b89-aa68-78643ab28079"} 2.761018 1747934296541
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/besteffort/pod84f30457-94e4-4b89-aa68-78643ab28079/c75319d6ef57a3b98ec5e13709da07d36f75a45121d5ab8ce1325aafb6baea08"} 2.754809 1747934299815
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/besteffort/pod84f30457-94e4-4b89-aa68-78643ab28079/f9441d008bb0ef186f59a79e60abf6ab761c537b667155da8707670922f1f920"} 0.011984 1747934310128
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/besteffort/pod8fbf0b7c-a364-42be-8bef-fefd57d0d292"} 0.075933 1747934274331
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/besteffort/pod8fbf0b7c-a364-42be-8bef-fefd57d0d292/283d235a9921bc2621fc58eaad290302e0f389210c6c84e65938c51f9c1d0603"} 0.043897 1747934318137
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/besteffort/pod8fbf0b7c-a364-42be-8bef-fefd57d0d292/efb0b0f775efdd99d273eb685bff3f03b2b00db01350027a154418f9ef561e1c"} 0.032036 1747934309484
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/besteffort/podb60dd11d-b886-4f97-8e36-ff9cf01e4d3b"} 7.708157 1747934312086
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/besteffort/podb60dd11d-b886-4f97-8e36-ff9cf01e4d3b/5e9406de9a6c9d47a1e21a3155c0585dcfd96a8467b8217891d23a0d941879c9"} 0.038612 1747934278030
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/besteffort/podb60dd11d-b886-4f97-8e36-ff9cf01e4d3b/622b149eec4415754388cab6d1beaca7ebff3401c8d07e1315c3241b2c6e2efd"} 7.663414 1747934307944
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/besteffort/podf311d12f-7dee-4286-935d-5dbd44cf2956"} 0.879519 1747934314573
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/besteffort/podf311d12f-7dee-4286-935d-5dbd44cf2956/433b86c0f7eead52b616f9469675b6fe0f9de2d8be9c8fe0776465a5b5fbfb0b"} 0.832491 1747934292499
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/besteffort/podf311d12f-7dee-4286-935d-5dbd44cf2956/728cc588f21ef9310b4394cbb5c6cbc664c8ded6c836583cad3bd0d60564646e"} 0.04585 1747934307846
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/burstable"} 209.261367 1747934274407
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/burstable/pod1f7ef46a-2bfb-4fd3-ae62-bfd74a3f6b8f"} 6.532485 1747934309673
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/burstable/pod1f7ef46a-2bfb-4fd3-ae62-bfd74a3f6b8f/9b103766e8c0208e5858d2e020964ecde34d007d463330cc2acbf37c0f468d3f"} 6.476208 1747934292673
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/burstable/pod1f7ef46a-2bfb-4fd3-ae62-bfd74a3f6b8f/c095de49603a07429ed5dd733c127f2724a32b3fc72400b5a61a05654894c624"} 0.036159 1747934312245
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/burstable/pod644033ef-97b2-4bee-8775-a8ff269c6bf8"} 16.979526 1747934299817
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/burstable/pod644033ef-97b2-4bee-8775-a8ff269c6bf8/06030b444348c0114ccd8be9f86ddec927cb41abef0bf7c8ef0a6f5fb165ab4b"} 16.951469 1747934304994
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/burstable/pod644033ef-97b2-4bee-8775-a8ff269c6bf8/f2604a6a35206db9fb21b4138d85f2e2d7948685aa0c6bacfa5c6defc490afe3"} 0.039858 1747934310575
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/burstable/pod8be9c1e0-4d98-4f9e-aac4-a17315ab00d3"} 141.017731 1747934298756
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/burstable/pod8be9c1e0-4d98-4f9e-aac4-a17315ab00d3/10b512431257c354ef2c5a6146eba83a49764b24668aa8d86a0f2339c20f535e"} 140.209146 1747934286747
container_cpu_usage_seconds_total{cpu="total",id="/kubepods/burstable/pod8be9c1e0-4d98-4f9e-aac4-a17315ab00d3/120478e451097d30c9f50ca1b544a02726199875e255c594bf389f145b07aff0"} 0.018175 1747934292257
container_cpu_usage_seconds_total{cpu="total",id="/system.slice"} 878.6111 1747934310837
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/ModemManager.service"} 0.089756 1747934311904
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/acpid.service"} 0.002034 1747934318711
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/chrony.service"} 0.254428 1747934289201
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/cloud-init.service"} 1.297278 1747934302570
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/cron.service"} 0.091089 1747934289224
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/dbus.service"} 0.722955 1747934308927
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/irqbalance.service"} 0.204311 1747934277106
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/lxd-installer.socket"} 0.00056 1747934273535
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/multipathd.service"} 0.422843 1747934298105
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/networkd-dispatcher.service"} 0.674913 1747934260772
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/polkit.service"} 0.240271 1747934305811
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/rsyslog.service"} 0.562453 1747934313641
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/snap.amazon-ssm-agent.amazon-ssm-agent.service"} 0.960221 1747934310259
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/snap.microk8s.daemon-apiserver-kicker.service"} 226.915576 1747934264672
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/snap.microk8s.daemon-cluster-agent.service"} 4.111194 1747934272798
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/snap.microk8s.daemon-containerd.service"} 170.761935 1747934269666
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/snap.microk8s.daemon-k8s-dqlite.service"} 84.017351 1747934311337
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/snap.microk8s.daemon-kubelite.service"} 242.756327 1747934309268
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/snapd.service"} 27.908894 1747934305447
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/snapd.socket"} 0.000278 1747934266573
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/ssh.service"} 0.301591 1747934288125
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/ssh.socket"} 0.00054 1747934283863
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/system-getty.slice"} 0.093742 1747934281798
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/system-getty.slice/getty@tty1.service"} 0.093742 1747934273340
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/system-modprobe.slice"} 0.037291 1747934285192
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/system-serial\\x2dgetty.slice"} 0.012008 1747934274842
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/system-serial\\x2dgetty.slice/serial-getty@ttyS0.service"} 0.012008 1747934286023
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/system-systemd\\x2dfsck.slice"} 0.034505 1747934317673
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/systemd-journald.service"} 2.086387 1747934288805
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/systemd-logind.service"} 0.241856 1747934289185
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/systemd-networkd.service"} 0.139306 1747934314015
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/systemd-resolved.service"} 0.652894 1747934316441
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/systemd-udevd.service"} 2.723107 1747934292263
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/systemd-udevd.service/udev"} 2.723107 1747934316149
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/udisks2.service"} 0.468286 1747934317273
container_cpu_usage_seconds_total{cpu="total",id="/system.slice/unattended-upgrades.service"} 0.09291 1747934318231
container_cpu_usage_seconds_total{cpu="total",id="/user.slice"} 32.660663 1747934318776
container_cpu_usage_seconds_total{cpu="total",id="/user.slice/user-1000.slice"} 5.028325 1747934298818
container_cpu_usage_seconds_total{cpu="total",id="/user.slice/user-1000.slice/session-12.scope"} 4.433995 1747934283375
container_cpu_usage_seconds_total{cpu="total",id="/user.slice/user-1000.slice/user@1000.service"} 0.482062 1747934262163
container_cpu_usage_seconds_total{cpu="total",id="/user.slice/user-1000.slice/user@1000.service/app.slice"} 0.023111 1747934312365
container_cpu_usage_seconds_total{cpu="total",id="/user.slice/user-1000.slice/user@1000.service/app.slice/dbus.socket"} 0.008584 1747934278351
container_cpu_usage_seconds_total{cpu="total",id="/user.slice/user-1000.slice/user@1000.service/app.slice/gpg-agent-ssh.socket"} 0.014527 1747934307824
container_cpu_usage_seconds_total{cpu="total",id="/user.slice/user-1000.slice/user@1000.service/init.scope"} 0.45895 1747934306292
```
``
